// Code generated by ent, DO NOT EDIT.

package predicate

import (
	"entgo.io/ent/dialect/sql"
)

// Crypto is the predicate function for crypto builders.
type Crypto func(*sql.Selector)

// Example is the predicate function for example builders.
type Example func(*sql.Selector)
