// Code generated by protoc-gen-go-redact. DO NOT EDIT.
// versions:
// - protoc-gen-go-redact v0.0.1
// - protoc             v5.29.3
// source: testdata/example.proto

package testdata

import (
	"encoding/json"

	"google.golang.org/protobuf/encoding/protojson"
)

// redact returns a map representation with sensitive fields masked.
// This is used internally for recursive redaction without JSON escaping issues.
func (x *User) redact() map[string]any {
	if x == nil {
		return nil
	}
	m := make(map[string]any)
	m["name"] = x.Name
	m["email"] = "*"
	m["password"] = "[HIDDEN]"
	m["age"] = x.Age
	return m
}

// Redact returns a redacted JSON string representation of User.
// Sensitive fields are masked to prevent accidental logging of sensitive data.
// This method implements the Redacter interface for Kratos logging middleware.
func (x *User) Redact() string {
	if x == nil {
		return "{}"
	}
	b, _ := json.Marshal(x.redact())
	return string(b)
}

// redact returns a map representation with sensitive fields masked.
// This is used internally for recursive redaction without JSON escaping issues.
func (x *Account) redact() map[string]any {
	if x == nil {
		return nil
	}
	m := make(map[string]any)
	m["id"] = x.Id
	m["secretKey"] = "***SECRET***"
	if x.User != nil {
		if r, ok := any(x.User).(interface{ redact() map[string]any }); ok {
			m["user"] = r.redact()
		} else {
			m["user"] = json.RawMessage(protojson.Format(x.User))
		}
	}
	return m
}

// Redact returns a redacted JSON string representation of Account.
// Sensitive fields are masked to prevent accidental logging of sensitive data.
// This method implements the Redacter interface for Kratos logging middleware.
func (x *Account) Redact() string {
	if x == nil {
		return "{}"
	}
	b, _ := json.Marshal(x.redact())
	return string(b)
}

// redact returns a map representation with sensitive fields masked.
// This is used internally for recursive redaction without JSON escaping issues.
func (x *Address) redact() map[string]any {
	if x == nil {
		return nil
	}
	m := make(map[string]any)
	m["street"] = x.Street
	m["city"] = x.City
	m["zipCode"] = "[ZIP]"
	return m
}

// Redact returns a redacted JSON string representation of Address.
// Sensitive fields are masked to prevent accidental logging of sensitive data.
// This method implements the Redacter interface for Kratos logging middleware.
func (x *Address) Redact() string {
	if x == nil {
		return "{}"
	}
	b, _ := json.Marshal(x.redact())
	return string(b)
}

// redact returns a map representation with sensitive fields masked.
// This is used internally for recursive redaction without JSON escaping issues.
func (x *Department) redact() map[string]any {
	if x == nil {
		return nil
	}
	m := make(map[string]any)
	m["name"] = x.Name
	m["budget"] = "[BUDGET]"
	if len(x.Accounts) > 0 {
		items := make([]any, len(x.Accounts))
		for i, item := range x.Accounts {
			if item != nil {
				if r, ok := any(item).(interface{ redact() map[string]any }); ok {
					items[i] = r.redact()
				} else {
					items[i] = json.RawMessage(protojson.Format(item))
				}
			}
		}
		m["accounts"] = items
	}
	if x.Address != nil {
		if r, ok := any(x.Address).(interface{ redact() map[string]any }); ok {
			m["address"] = r.redact()
		} else {
			m["address"] = json.RawMessage(protojson.Format(x.Address))
		}
	}
	return m
}

// Redact returns a redacted JSON string representation of Department.
// Sensitive fields are masked to prevent accidental logging of sensitive data.
// This method implements the Redacter interface for Kratos logging middleware.
func (x *Department) Redact() string {
	if x == nil {
		return "{}"
	}
	b, _ := json.Marshal(x.redact())
	return string(b)
}

// redact returns a map representation with sensitive fields masked.
// This is used internally for recursive redaction without JSON escaping issues.
func (x *Organization) redact() map[string]any {
	if x == nil {
		return nil
	}
	m := make(map[string]any)
	m["name"] = x.Name
	m["taxId"] = x.TaxId
	if len(x.Departments) > 0 {
		items := make([]any, len(x.Departments))
		for i, item := range x.Departments {
			if item != nil {
				if r, ok := any(item).(interface{ redact() map[string]any }); ok {
					items[i] = r.redact()
				} else {
					items[i] = json.RawMessage(protojson.Format(item))
				}
			}
		}
		m["departments"] = items
	}
	if x.Headquarters != nil {
		if r, ok := any(x.Headquarters).(interface{ redact() map[string]any }); ok {
			m["headquarters"] = r.redact()
		} else {
			m["headquarters"] = json.RawMessage(protojson.Format(x.Headquarters))
		}
	}
	return m
}

// Redact returns a redacted JSON string representation of Organization.
// Sensitive fields are masked to prevent accidental logging of sensitive data.
// This method implements the Redacter interface for Kratos logging middleware.
func (x *Organization) Redact() string {
	if x == nil {
		return "{}"
	}
	b, _ := json.Marshal(x.redact())
	return string(b)
}

// redact returns a map representation with sensitive fields masked.
// This is used internally for recursive redaction without JSON escaping issues.
func (x *Event) redact() map[string]any {
	if x == nil {
		return nil
	}
	m := make(map[string]any)
	m["name"] = x.Name
	m["apiKey"] = "*"
	if x.CreatedAt != nil {
		if r, ok := any(x.CreatedAt).(interface{ redact() map[string]any }); ok {
			m["createdAt"] = r.redact()
		} else {
			m["createdAt"] = json.RawMessage(protojson.Format(x.CreatedAt))
		}
	}
	if x.UpdatedAt != nil {
		if r, ok := any(x.UpdatedAt).(interface{ redact() map[string]any }); ok {
			m["updatedAt"] = r.redact()
		} else {
			m["updatedAt"] = json.RawMessage(protojson.Format(x.UpdatedAt))
		}
	}
	return m
}

// Redact returns a redacted JSON string representation of Event.
// Sensitive fields are masked to prevent accidental logging of sensitive data.
// This method implements the Redacter interface for Kratos logging middleware.
func (x *Event) Redact() string {
	if x == nil {
		return "{}"
	}
	b, _ := json.Marshal(x.redact())
	return string(b)
}

// redact returns a map representation with sensitive fields masked.
// This is used internally for recursive redaction without JSON escaping issues.
func (x *Payment) redact() map[string]any {
	if x == nil {
		return nil
	}
	m := make(map[string]any)
	m["id"] = x.Id
	m["amount"] = "[AMOUNT]"
	m["balance"] = "[BALANCE]"
	m["pinCode"] = "*"
	m["currency"] = x.Currency
	if len(x.CardNumbers) > 0 {
		m["cardNumbers"] = x.CardNumbers
	}
	if len(x.TransactionIds) > 0 {
		m["transactionIds"] = x.TransactionIds
	}
	return m
}

// Redact returns a redacted JSON string representation of Payment.
// Sensitive fields are masked to prevent accidental logging of sensitive data.
// This method implements the Redacter interface for Kratos logging middleware.
func (x *Payment) Redact() string {
	if x == nil {
		return "{}"
	}
	b, _ := json.Marshal(x.redact())
	return string(b)
}

// redact returns a map representation with sensitive fields masked.
// This is used internally for recursive redaction without JSON escaping issues.
func (x *Wrapper) redact() map[string]any {
	if x == nil {
		return nil
	}
	m := make(map[string]any)
	m["id"] = x.Id
	m["name"] = x.Name
	if x.User != nil {
		if r, ok := any(x.User).(interface{ redact() map[string]any }); ok {
			m["user"] = r.redact()
		} else {
			m["user"] = json.RawMessage(protojson.Format(x.User))
		}
	}
	if len(x.Accounts) > 0 {
		items := make([]any, len(x.Accounts))
		for i, item := range x.Accounts {
			if item != nil {
				if r, ok := any(item).(interface{ redact() map[string]any }); ok {
					items[i] = r.redact()
				} else {
					items[i] = json.RawMessage(protojson.Format(item))
				}
			}
		}
		m["accounts"] = items
	}
	return m
}

// Redact returns a redacted JSON string representation of Wrapper.
// Sensitive fields are masked to prevent accidental logging of sensitive data.
// This method implements the Redacter interface for Kratos logging middleware.
func (x *Wrapper) Redact() string {
	if x == nil {
		return "{}"
	}
	b, _ := json.Marshal(x.redact())
	return string(b)
}

// redact returns a map representation with sensitive fields masked.
// This is used internally for recursive redaction without JSON escaping issues.
func (x *SpecialChars) redact() map[string]any {
	if x == nil {
		return nil
	}
	m := make(map[string]any)
	m["normal"] = x.Normal
	m["withQuotes"] = "[REDACTED]"
	m["unicodeField"] = x.UnicodeField
	return m
}

// Redact returns a redacted JSON string representation of SpecialChars.
// Sensitive fields are masked to prevent accidental logging of sensitive data.
// This method implements the Redacter interface for Kratos logging middleware.
func (x *SpecialChars) Redact() string {
	if x == nil {
		return "{}"
	}
	b, _ := json.Marshal(x.redact())
	return string(b)
}

// redact returns a map representation with sensitive fields masked.
// This is used internally for recursive redaction without JSON escaping issues.
func (x *Container) redact() map[string]any {
	if x == nil {
		return nil
	}
	m := make(map[string]any)
	if x.User != nil {
		if r, ok := any(x.User).(interface{ redact() map[string]any }); ok {
			m["user"] = r.redact()
		} else {
			m["user"] = json.RawMessage(protojson.Format(x.User))
		}
	}
	if x.Address != nil {
		if r, ok := any(x.Address).(interface{ redact() map[string]any }); ok {
			m["address"] = r.redact()
		} else {
			m["address"] = json.RawMessage(protojson.Format(x.Address))
		}
	}
	return m
}

// Redact returns a redacted JSON string representation of Container.
// Sensitive fields are masked to prevent accidental logging of sensitive data.
// This method implements the Redacter interface for Kratos logging middleware.
func (x *Container) Redact() string {
	if x == nil {
		return "{}"
	}
	b, _ := json.Marshal(x.redact())
	return string(b)
}

// redact returns a map representation with sensitive fields masked.
// This is used internally for recursive redaction without JSON escaping issues.
func (x *Profile) redact() map[string]any {
	if x == nil {
		return nil
	}
	m := make(map[string]any)
	m["username"] = x.Username
	m["ssn"] = "[SSN]"
	m["isVerified"] = x.IsVerified
	m["status"] = x.Status
	if len(x.Tags) > 0 {
		m["tags"] = x.Tags
	}
	return m
}

// Redact returns a redacted JSON string representation of Profile.
// Sensitive fields are masked to prevent accidental logging of sensitive data.
// This method implements the Redacter interface for Kratos logging middleware.
func (x *Profile) Redact() string {
	if x == nil {
		return "{}"
	}
	b, _ := json.Marshal(x.redact())
	return string(b)
}
