// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.9
// 	protoc        v5.29.3
// source: testdata/example.proto

package testdata

import (
	_ "github.com/crypto-zero/go-kit/proto/kit/redact/v1"
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	timestamppb "google.golang.org/protobuf/types/known/timestamppb"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// Test with bool and enum types
type Status int32

const (
	Status_STATUS_UNSPECIFIED Status = 0
	Status_STATUS_ACTIVE      Status = 1
	Status_STATUS_INACTIVE    Status = 2
)

// Enum value maps for Status.
var (
	Status_name = map[int32]string{
		0: "STATUS_UNSPECIFIED",
		1: "STATUS_ACTIVE",
		2: "STATUS_INACTIVE",
	}
	Status_value = map[string]int32{
		"STATUS_UNSPECIFIED": 0,
		"STATUS_ACTIVE":      1,
		"STATUS_INACTIVE":    2,
	}
)

func (x Status) Enum() *Status {
	p := new(Status)
	*p = x
	return p
}

func (x Status) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (Status) Descriptor() protoreflect.EnumDescriptor {
	return file_testdata_example_proto_enumTypes[0].Descriptor()
}

func (Status) Type() protoreflect.EnumType {
	return &file_testdata_example_proto_enumTypes[0]
}

func (x Status) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use Status.Descriptor instead.
func (Status) EnumDescriptor() ([]byte, []int) {
	return file_testdata_example_proto_rawDescGZIP(), []int{0}
}

type User struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Name          string                 `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
	Email         string                 `protobuf:"bytes,2,opt,name=email,proto3" json:"email,omitempty"`
	Password      string                 `protobuf:"bytes,3,opt,name=password,proto3" json:"password,omitempty"`
	Age           int64                  `protobuf:"varint,4,opt,name=age,proto3" json:"age,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *User) Reset() {
	*x = User{}
	mi := &file_testdata_example_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *User) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*User) ProtoMessage() {}

func (x *User) ProtoReflect() protoreflect.Message {
	mi := &file_testdata_example_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use User.ProtoReflect.Descriptor instead.
func (*User) Descriptor() ([]byte, []int) {
	return file_testdata_example_proto_rawDescGZIP(), []int{0}
}

func (x *User) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *User) GetEmail() string {
	if x != nil {
		return x.Email
	}
	return ""
}

func (x *User) GetPassword() string {
	if x != nil {
		return x.Password
	}
	return ""
}

func (x *User) GetAge() int64 {
	if x != nil {
		return x.Age
	}
	return 0
}

type Account struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	SecretKey     string                 `protobuf:"bytes,2,opt,name=secret_key,json=secretKey,proto3" json:"secret_key,omitempty"`
	User          *User                  `protobuf:"bytes,3,opt,name=user,proto3" json:"user,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Account) Reset() {
	*x = Account{}
	mi := &file_testdata_example_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Account) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Account) ProtoMessage() {}

func (x *Account) ProtoReflect() protoreflect.Message {
	mi := &file_testdata_example_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Account.ProtoReflect.Descriptor instead.
func (*Account) Descriptor() ([]byte, []int) {
	return file_testdata_example_proto_rawDescGZIP(), []int{1}
}

func (x *Account) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *Account) GetSecretKey() string {
	if x != nil {
		return x.SecretKey
	}
	return ""
}

func (x *Account) GetUser() *User {
	if x != nil {
		return x.User
	}
	return nil
}

// Multi-level nested structure for testing
type Address struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Street        string                 `protobuf:"bytes,1,opt,name=street,proto3" json:"street,omitempty"`
	City          string                 `protobuf:"bytes,2,opt,name=city,proto3" json:"city,omitempty"`
	ZipCode       string                 `protobuf:"bytes,3,opt,name=zip_code,json=zipCode,proto3" json:"zip_code,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Address) Reset() {
	*x = Address{}
	mi := &file_testdata_example_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Address) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Address) ProtoMessage() {}

func (x *Address) ProtoReflect() protoreflect.Message {
	mi := &file_testdata_example_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Address.ProtoReflect.Descriptor instead.
func (*Address) Descriptor() ([]byte, []int) {
	return file_testdata_example_proto_rawDescGZIP(), []int{2}
}

func (x *Address) GetStreet() string {
	if x != nil {
		return x.Street
	}
	return ""
}

func (x *Address) GetCity() string {
	if x != nil {
		return x.City
	}
	return ""
}

func (x *Address) GetZipCode() string {
	if x != nil {
		return x.ZipCode
	}
	return ""
}

type Department struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Name          string                 `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
	Budget        string                 `protobuf:"bytes,2,opt,name=budget,proto3" json:"budget,omitempty"`
	Accounts      []*Account             `protobuf:"bytes,3,rep,name=accounts,proto3" json:"accounts,omitempty"`
	Address       *Address               `protobuf:"bytes,4,opt,name=address,proto3" json:"address,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Department) Reset() {
	*x = Department{}
	mi := &file_testdata_example_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Department) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Department) ProtoMessage() {}

func (x *Department) ProtoReflect() protoreflect.Message {
	mi := &file_testdata_example_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Department.ProtoReflect.Descriptor instead.
func (*Department) Descriptor() ([]byte, []int) {
	return file_testdata_example_proto_rawDescGZIP(), []int{3}
}

func (x *Department) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *Department) GetBudget() string {
	if x != nil {
		return x.Budget
	}
	return ""
}

func (x *Department) GetAccounts() []*Account {
	if x != nil {
		return x.Accounts
	}
	return nil
}

func (x *Department) GetAddress() *Address {
	if x != nil {
		return x.Address
	}
	return nil
}

type Organization struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Name          string                 `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
	TaxId         string                 `protobuf:"bytes,2,opt,name=tax_id,json=taxId,proto3" json:"tax_id,omitempty"`
	Departments   []*Department          `protobuf:"bytes,3,rep,name=departments,proto3" json:"departments,omitempty"`
	Headquarters  *Address               `protobuf:"bytes,4,opt,name=headquarters,proto3" json:"headquarters,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Organization) Reset() {
	*x = Organization{}
	mi := &file_testdata_example_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Organization) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Organization) ProtoMessage() {}

func (x *Organization) ProtoReflect() protoreflect.Message {
	mi := &file_testdata_example_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Organization.ProtoReflect.Descriptor instead.
func (*Organization) Descriptor() ([]byte, []int) {
	return file_testdata_example_proto_rawDescGZIP(), []int{4}
}

func (x *Organization) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *Organization) GetTaxId() string {
	if x != nil {
		return x.TaxId
	}
	return ""
}

func (x *Organization) GetDepartments() []*Department {
	if x != nil {
		return x.Departments
	}
	return nil
}

func (x *Organization) GetHeadquarters() *Address {
	if x != nil {
		return x.Headquarters
	}
	return nil
}

// Test with google.protobuf.Timestamp
type Event struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Name          string                 `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
	ApiKey        string                 `protobuf:"bytes,2,opt,name=api_key,json=apiKey,proto3" json:"api_key,omitempty"`
	CreatedAt     *timestamppb.Timestamp `protobuf:"bytes,3,opt,name=created_at,json=createdAt,proto3" json:"created_at,omitempty"`
	UpdatedAt     *timestamppb.Timestamp `protobuf:"bytes,4,opt,name=updated_at,json=updatedAt,proto3" json:"updated_at,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Event) Reset() {
	*x = Event{}
	mi := &file_testdata_example_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Event) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Event) ProtoMessage() {}

func (x *Event) ProtoReflect() protoreflect.Message {
	mi := &file_testdata_example_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Event.ProtoReflect.Descriptor instead.
func (*Event) Descriptor() ([]byte, []int) {
	return file_testdata_example_proto_rawDescGZIP(), []int{5}
}

func (x *Event) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *Event) GetApiKey() string {
	if x != nil {
		return x.ApiKey
	}
	return ""
}

func (x *Event) GetCreatedAt() *timestamppb.Timestamp {
	if x != nil {
		return x.CreatedAt
	}
	return nil
}

func (x *Event) GetUpdatedAt() *timestamppb.Timestamp {
	if x != nil {
		return x.UpdatedAt
	}
	return nil
}

// Test with numeric types and repeated primitives
type Payment struct {
	state          protoimpl.MessageState `protogen:"open.v1"`
	Id             string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	Amount         int64                  `protobuf:"varint,2,opt,name=amount,proto3" json:"amount,omitempty"`
	Balance        float64                `protobuf:"fixed64,3,opt,name=balance,proto3" json:"balance,omitempty"`
	PinCode        int32                  `protobuf:"varint,4,opt,name=pin_code,json=pinCode,proto3" json:"pin_code,omitempty"`
	Currency       string                 `protobuf:"bytes,5,opt,name=currency,proto3" json:"currency,omitempty"`
	CardNumbers    []string               `protobuf:"bytes,6,rep,name=card_numbers,json=cardNumbers,proto3" json:"card_numbers,omitempty"`
	TransactionIds []int64                `protobuf:"varint,7,rep,packed,name=transaction_ids,json=transactionIds,proto3" json:"transaction_ids,omitempty"`
	unknownFields  protoimpl.UnknownFields
	sizeCache      protoimpl.SizeCache
}

func (x *Payment) Reset() {
	*x = Payment{}
	mi := &file_testdata_example_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Payment) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Payment) ProtoMessage() {}

func (x *Payment) ProtoReflect() protoreflect.Message {
	mi := &file_testdata_example_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Payment.ProtoReflect.Descriptor instead.
func (*Payment) Descriptor() ([]byte, []int) {
	return file_testdata_example_proto_rawDescGZIP(), []int{6}
}

func (x *Payment) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *Payment) GetAmount() int64 {
	if x != nil {
		return x.Amount
	}
	return 0
}

func (x *Payment) GetBalance() float64 {
	if x != nil {
		return x.Balance
	}
	return 0
}

func (x *Payment) GetPinCode() int32 {
	if x != nil {
		return x.PinCode
	}
	return 0
}

func (x *Payment) GetCurrency() string {
	if x != nil {
		return x.Currency
	}
	return ""
}

func (x *Payment) GetCardNumbers() []string {
	if x != nil {
		return x.CardNumbers
	}
	return nil
}

func (x *Payment) GetTransactionIds() []int64 {
	if x != nil {
		return x.TransactionIds
	}
	return nil
}

// Test wrapper without own redact fields (should still generate Redact for nested)
type Wrapper struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	Name          string                 `protobuf:"bytes,2,opt,name=name,proto3" json:"name,omitempty"`
	User          *User                  `protobuf:"bytes,3,opt,name=user,proto3" json:"user,omitempty"`
	Accounts      []*Account             `protobuf:"bytes,4,rep,name=accounts,proto3" json:"accounts,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Wrapper) Reset() {
	*x = Wrapper{}
	mi := &file_testdata_example_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Wrapper) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Wrapper) ProtoMessage() {}

func (x *Wrapper) ProtoReflect() protoreflect.Message {
	mi := &file_testdata_example_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Wrapper.ProtoReflect.Descriptor instead.
func (*Wrapper) Descriptor() ([]byte, []int) {
	return file_testdata_example_proto_rawDescGZIP(), []int{7}
}

func (x *Wrapper) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *Wrapper) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *Wrapper) GetUser() *User {
	if x != nil {
		return x.User
	}
	return nil
}

func (x *Wrapper) GetAccounts() []*Account {
	if x != nil {
		return x.Accounts
	}
	return nil
}

// Test with special characters in values
type SpecialChars struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Normal        string                 `protobuf:"bytes,1,opt,name=normal,proto3" json:"normal,omitempty"`
	WithQuotes    string                 `protobuf:"bytes,2,opt,name=with_quotes,json=withQuotes,proto3" json:"with_quotes,omitempty"`
	UnicodeField  string                 `protobuf:"bytes,3,opt,name=unicode_field,json=unicodeField,proto3" json:"unicode_field,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SpecialChars) Reset() {
	*x = SpecialChars{}
	mi := &file_testdata_example_proto_msgTypes[8]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SpecialChars) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SpecialChars) ProtoMessage() {}

func (x *SpecialChars) ProtoReflect() protoreflect.Message {
	mi := &file_testdata_example_proto_msgTypes[8]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SpecialChars.ProtoReflect.Descriptor instead.
func (*SpecialChars) Descriptor() ([]byte, []int) {
	return file_testdata_example_proto_rawDescGZIP(), []int{8}
}

func (x *SpecialChars) GetNormal() string {
	if x != nil {
		return x.Normal
	}
	return ""
}

func (x *SpecialChars) GetWithQuotes() string {
	if x != nil {
		return x.WithQuotes
	}
	return ""
}

func (x *SpecialChars) GetUnicodeField() string {
	if x != nil {
		return x.UnicodeField
	}
	return ""
}

// Test empty message with only message fields
type Container struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	User          *User                  `protobuf:"bytes,1,opt,name=user,proto3" json:"user,omitempty"`
	Address       *Address               `protobuf:"bytes,2,opt,name=address,proto3" json:"address,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Container) Reset() {
	*x = Container{}
	mi := &file_testdata_example_proto_msgTypes[9]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Container) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Container) ProtoMessage() {}

func (x *Container) ProtoReflect() protoreflect.Message {
	mi := &file_testdata_example_proto_msgTypes[9]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Container.ProtoReflect.Descriptor instead.
func (*Container) Descriptor() ([]byte, []int) {
	return file_testdata_example_proto_rawDescGZIP(), []int{9}
}

func (x *Container) GetUser() *User {
	if x != nil {
		return x.User
	}
	return nil
}

func (x *Container) GetAddress() *Address {
	if x != nil {
		return x.Address
	}
	return nil
}

type Profile struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Username      string                 `protobuf:"bytes,1,opt,name=username,proto3" json:"username,omitempty"`
	Ssn           string                 `protobuf:"bytes,2,opt,name=ssn,proto3" json:"ssn,omitempty"`
	IsVerified    bool                   `protobuf:"varint,3,opt,name=is_verified,json=isVerified,proto3" json:"is_verified,omitempty"`
	Status        Status                 `protobuf:"varint,4,opt,name=status,proto3,enum=testdata.Status" json:"status,omitempty"`
	Tags          []string               `protobuf:"bytes,5,rep,name=tags,proto3" json:"tags,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Profile) Reset() {
	*x = Profile{}
	mi := &file_testdata_example_proto_msgTypes[10]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Profile) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Profile) ProtoMessage() {}

func (x *Profile) ProtoReflect() protoreflect.Message {
	mi := &file_testdata_example_proto_msgTypes[10]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Profile.ProtoReflect.Descriptor instead.
func (*Profile) Descriptor() ([]byte, []int) {
	return file_testdata_example_proto_rawDescGZIP(), []int{10}
}

func (x *Profile) GetUsername() string {
	if x != nil {
		return x.Username
	}
	return ""
}

func (x *Profile) GetSsn() string {
	if x != nil {
		return x.Ssn
	}
	return ""
}

func (x *Profile) GetIsVerified() bool {
	if x != nil {
		return x.IsVerified
	}
	return false
}

func (x *Profile) GetStatus() Status {
	if x != nil {
		return x.Status
	}
	return Status_STATUS_UNSPECIFIED
}

func (x *Profile) GetTags() []string {
	if x != nil {
		return x.Tags
	}
	return nil
}

var File_testdata_example_proto protoreflect.FileDescriptor

const file_testdata_example_proto_rawDesc = "" +
	"\n" +
	"\x16testdata/example.proto\x12\btestdata\x1a\x1fgoogle/protobuf/timestamp.proto\x1a\x1akit/redact/v1/redact.proto\"x\n" +
	"\x04User\x12\x12\n" +
	"\x04name\x18\x01 \x01(\tR\x04name\x12\x1c\n" +
	"\x05email\x18\x02 \x01(\tB\x06¢3\x02\b\x01R\x05email\x12,\n" +
	"\bpassword\x18\x03 \x01(\tB\x10¢3\f\b\x01\x12\b[HIDDEN]R\bpassword\x12\x10\n" +
	"\x03age\x18\x04 \x01(\x03R\x03age\"r\n" +
	"\aAccount\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\x123\n" +
	"\n" +
	"secret_key\x18\x02 \x01(\tB\x14¢3\x10\b\x01\x12\f***SECRET***R\tsecretKey\x12\"\n" +
	"\x04user\x18\x03 \x01(\v2\x0e.testdata.UserR\x04user\"_\n" +
	"\aAddress\x12\x16\n" +
	"\x06street\x18\x01 \x01(\tR\x06street\x12\x12\n" +
	"\x04city\x18\x02 \x01(\tR\x04city\x12(\n" +
	"\bzip_code\x18\x03 \x01(\tB\r¢3\t\b\x01\x12\x05[ZIP]R\azipCode\"\xa6\x01\n" +
	"\n" +
	"Department\x12\x12\n" +
	"\x04name\x18\x01 \x01(\tR\x04name\x12(\n" +
	"\x06budget\x18\x02 \x01(\tB\x10¢3\f\b\x01\x12\b[BUDGET]R\x06budget\x12-\n" +
	"\baccounts\x18\x03 \x03(\v2\x11.testdata.AccountR\baccounts\x12+\n" +
	"\aaddress\x18\x04 \x01(\v2\x11.testdata.AddressR\aaddress\"\xa8\x01\n" +
	"\fOrganization\x12\x12\n" +
	"\x04name\x18\x01 \x01(\tR\x04name\x12\x15\n" +
	"\x06tax_id\x18\x02 \x01(\tR\x05taxId\x126\n" +
	"\vdepartments\x18\x03 \x03(\v2\x14.testdata.DepartmentR\vdepartments\x125\n" +
	"\fheadquarters\x18\x04 \x01(\v2\x11.testdata.AddressR\fheadquarters\"\xb2\x01\n" +
	"\x05Event\x12\x12\n" +
	"\x04name\x18\x01 \x01(\tR\x04name\x12\x1f\n" +
	"\aapi_key\x18\x02 \x01(\tB\x06¢3\x02\b\x01R\x06apiKey\x129\n" +
	"\n" +
	"created_at\x18\x03 \x01(\v2\x1a.google.protobuf.TimestampR\tcreatedAt\x129\n" +
	"\n" +
	"updated_at\x18\x04 \x01(\v2\x1a.google.protobuf.TimestampR\tupdatedAt\"\xfb\x01\n" +
	"\aPayment\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\x12(\n" +
	"\x06amount\x18\x02 \x01(\x03B\x10¢3\f\b\x01\x12\b[AMOUNT]R\x06amount\x12+\n" +
	"\abalance\x18\x03 \x01(\x01B\x11¢3\r\b\x01\x12\t[BALANCE]R\abalance\x12!\n" +
	"\bpin_code\x18\x04 \x01(\x05B\x06¢3\x02\b\x01R\apinCode\x12\x1a\n" +
	"\bcurrency\x18\x05 \x01(\tR\bcurrency\x12!\n" +
	"\fcard_numbers\x18\x06 \x03(\tR\vcardNumbers\x12'\n" +
	"\x0ftransaction_ids\x18\a \x03(\x03R\x0etransactionIds\"\x80\x01\n" +
	"\aWrapper\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\x12\x12\n" +
	"\x04name\x18\x02 \x01(\tR\x04name\x12\"\n" +
	"\x04user\x18\x03 \x01(\v2\x0e.testdata.UserR\x04user\x12-\n" +
	"\baccounts\x18\x04 \x03(\v2\x11.testdata.AccountR\baccounts\"\x80\x01\n" +
	"\fSpecialChars\x12\x16\n" +
	"\x06normal\x18\x01 \x01(\tR\x06normal\x123\n" +
	"\vwith_quotes\x18\x02 \x01(\tB\x12¢3\x0e\b\x01\x12\n" +
	"[REDACTED]R\n" +
	"withQuotes\x12#\n" +
	"\runicode_field\x18\x03 \x01(\tR\funicodeField\"\\\n" +
	"\tContainer\x12\"\n" +
	"\x04user\x18\x01 \x01(\v2\x0e.testdata.UserR\x04user\x12+\n" +
	"\aaddress\x18\x02 \x01(\v2\x11.testdata.AddressR\aaddress\"\xa5\x01\n" +
	"\aProfile\x12\x1a\n" +
	"\busername\x18\x01 \x01(\tR\busername\x12\x1f\n" +
	"\x03ssn\x18\x02 \x01(\tB\r¢3\t\b\x01\x12\x05[SSN]R\x03ssn\x12\x1f\n" +
	"\vis_verified\x18\x03 \x01(\bR\n" +
	"isVerified\x12(\n" +
	"\x06status\x18\x04 \x01(\x0e2\x10.testdata.StatusR\x06status\x12\x12\n" +
	"\x04tags\x18\x05 \x03(\tR\x04tags*H\n" +
	"\x06Status\x12\x16\n" +
	"\x12STATUS_UNSPECIFIED\x10\x00\x12\x11\n" +
	"\rSTATUS_ACTIVE\x10\x01\x12\x13\n" +
	"\x0fSTATUS_INACTIVE\x10\x02BEZCgithub.com/crypto-zero/go-kit/logging/protoc-gen-go-redact/testdatab\x06proto3"

var (
	file_testdata_example_proto_rawDescOnce sync.Once
	file_testdata_example_proto_rawDescData []byte
)

func file_testdata_example_proto_rawDescGZIP() []byte {
	file_testdata_example_proto_rawDescOnce.Do(func() {
		file_testdata_example_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_testdata_example_proto_rawDesc), len(file_testdata_example_proto_rawDesc)))
	})
	return file_testdata_example_proto_rawDescData
}

var file_testdata_example_proto_enumTypes = make([]protoimpl.EnumInfo, 1)
var file_testdata_example_proto_msgTypes = make([]protoimpl.MessageInfo, 11)
var file_testdata_example_proto_goTypes = []any{
	(Status)(0),                   // 0: testdata.Status
	(*User)(nil),                  // 1: testdata.User
	(*Account)(nil),               // 2: testdata.Account
	(*Address)(nil),               // 3: testdata.Address
	(*Department)(nil),            // 4: testdata.Department
	(*Organization)(nil),          // 5: testdata.Organization
	(*Event)(nil),                 // 6: testdata.Event
	(*Payment)(nil),               // 7: testdata.Payment
	(*Wrapper)(nil),               // 8: testdata.Wrapper
	(*SpecialChars)(nil),          // 9: testdata.SpecialChars
	(*Container)(nil),             // 10: testdata.Container
	(*Profile)(nil),               // 11: testdata.Profile
	(*timestamppb.Timestamp)(nil), // 12: google.protobuf.Timestamp
}
var file_testdata_example_proto_depIdxs = []int32{
	1,  // 0: testdata.Account.user:type_name -> testdata.User
	2,  // 1: testdata.Department.accounts:type_name -> testdata.Account
	3,  // 2: testdata.Department.address:type_name -> testdata.Address
	4,  // 3: testdata.Organization.departments:type_name -> testdata.Department
	3,  // 4: testdata.Organization.headquarters:type_name -> testdata.Address
	12, // 5: testdata.Event.created_at:type_name -> google.protobuf.Timestamp
	12, // 6: testdata.Event.updated_at:type_name -> google.protobuf.Timestamp
	1,  // 7: testdata.Wrapper.user:type_name -> testdata.User
	2,  // 8: testdata.Wrapper.accounts:type_name -> testdata.Account
	1,  // 9: testdata.Container.user:type_name -> testdata.User
	3,  // 10: testdata.Container.address:type_name -> testdata.Address
	0,  // 11: testdata.Profile.status:type_name -> testdata.Status
	12, // [12:12] is the sub-list for method output_type
	12, // [12:12] is the sub-list for method input_type
	12, // [12:12] is the sub-list for extension type_name
	12, // [12:12] is the sub-list for extension extendee
	0,  // [0:12] is the sub-list for field type_name
}

func init() { file_testdata_example_proto_init() }
func file_testdata_example_proto_init() {
	if File_testdata_example_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_testdata_example_proto_rawDesc), len(file_testdata_example_proto_rawDesc)),
			NumEnums:      1,
			NumMessages:   11,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_testdata_example_proto_goTypes,
		DependencyIndexes: file_testdata_example_proto_depIdxs,
		EnumInfos:         file_testdata_example_proto_enumTypes,
		MessageInfos:      file_testdata_example_proto_msgTypes,
	}.Build()
	File_testdata_example_proto = out.File
	file_testdata_example_proto_goTypes = nil
	file_testdata_example_proto_depIdxs = nil
}
