// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.9
// 	protoc        v5.29.3
// source: kit/redact/v1/redact.proto

package redact

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	descriptorpb "google.golang.org/protobuf/types/descriptorpb"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// RedactOptions configures how a field should be redacted.
//
// Scalar types support custom mask values:
//   - string: custom via string_mask, default "*"
//   - bytes: custom via bytes_mask, default ""
//   - enum: custom via enum_mask, default 0
//   - int32/int64/uint32/uint64/sint32/sint64: custom via int_mask, default 0
//   - fixed32/fixed64/sfixed32/sfixed64: custom via int_mask, default 0
//   - float/double: custom via double_mask, default 0
//   - bool: custom via bool_mask, default false
//
// Composite types always use default values (no custom mask):
//   - message: null
//   - repeated (any type): []
//   - map (any type): {}
type RedactOptions struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// If true, this field will be redacted in logs.
	Redact bool `protobuf:"varint,1,opt,name=redact,proto3" json:"redact,omitempty"`
	// Custom mask values for scalar field types only.
	// Use the appropriate field based on your field's type.
	// Composite types (message, repeated, map) always use default values.
	//
	// Types that are valid to be assigned to MaskValue:
	//
	//	*RedactOptions_StringMask
	//	*RedactOptions_IntMask
	//	*RedactOptions_DoubleMask
	//	*RedactOptions_BoolMask
	//	*RedactOptions_BytesMask
	//	*RedactOptions_EnumMask
	MaskValue     isRedactOptions_MaskValue `protobuf_oneof:"mask_value"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *RedactOptions) Reset() {
	*x = RedactOptions{}
	mi := &file_kit_redact_v1_redact_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RedactOptions) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RedactOptions) ProtoMessage() {}

func (x *RedactOptions) ProtoReflect() protoreflect.Message {
	mi := &file_kit_redact_v1_redact_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RedactOptions.ProtoReflect.Descriptor instead.
func (*RedactOptions) Descriptor() ([]byte, []int) {
	return file_kit_redact_v1_redact_proto_rawDescGZIP(), []int{0}
}

func (x *RedactOptions) GetRedact() bool {
	if x != nil {
		return x.Redact
	}
	return false
}

func (x *RedactOptions) GetMaskValue() isRedactOptions_MaskValue {
	if x != nil {
		return x.MaskValue
	}
	return nil
}

func (x *RedactOptions) GetStringMask() string {
	if x != nil {
		if x, ok := x.MaskValue.(*RedactOptions_StringMask); ok {
			return x.StringMask
		}
	}
	return ""
}

func (x *RedactOptions) GetIntMask() int64 {
	if x != nil {
		if x, ok := x.MaskValue.(*RedactOptions_IntMask); ok {
			return x.IntMask
		}
	}
	return 0
}

func (x *RedactOptions) GetDoubleMask() float64 {
	if x != nil {
		if x, ok := x.MaskValue.(*RedactOptions_DoubleMask); ok {
			return x.DoubleMask
		}
	}
	return 0
}

func (x *RedactOptions) GetBoolMask() bool {
	if x != nil {
		if x, ok := x.MaskValue.(*RedactOptions_BoolMask); ok {
			return x.BoolMask
		}
	}
	return false
}

func (x *RedactOptions) GetBytesMask() string {
	if x != nil {
		if x, ok := x.MaskValue.(*RedactOptions_BytesMask); ok {
			return x.BytesMask
		}
	}
	return ""
}

func (x *RedactOptions) GetEnumMask() int32 {
	if x != nil {
		if x, ok := x.MaskValue.(*RedactOptions_EnumMask); ok {
			return x.EnumMask
		}
	}
	return 0
}

type isRedactOptions_MaskValue interface {
	isRedactOptions_MaskValue()
}

type RedactOptions_StringMask struct {
	StringMask string `protobuf:"bytes,2,opt,name=string_mask,json=stringMask,proto3,oneof"` // For string fields. Default: "*"
}

type RedactOptions_IntMask struct {
	IntMask int64 `protobuf:"varint,3,opt,name=int_mask,json=intMask,proto3,oneof"` // For all integer types. Default: 0
}

type RedactOptions_DoubleMask struct {
	DoubleMask float64 `protobuf:"fixed64,4,opt,name=double_mask,json=doubleMask,proto3,oneof"` // For float/double fields. Default: 0
}

type RedactOptions_BoolMask struct {
	BoolMask bool `protobuf:"varint,5,opt,name=bool_mask,json=boolMask,proto3,oneof"` // For bool fields. Default: false
}

type RedactOptions_BytesMask struct {
	BytesMask string `protobuf:"bytes,6,opt,name=bytes_mask,json=bytesMask,proto3,oneof"` // For bytes fields. Default: ""
}

type RedactOptions_EnumMask struct {
	EnumMask int32 `protobuf:"varint,7,opt,name=enum_mask,json=enumMask,proto3,oneof"` // For enum fields. Default: 0
}

func (*RedactOptions_StringMask) isRedactOptions_MaskValue() {}

func (*RedactOptions_IntMask) isRedactOptions_MaskValue() {}

func (*RedactOptions_DoubleMask) isRedactOptions_MaskValue() {}

func (*RedactOptions_BoolMask) isRedactOptions_MaskValue() {}

func (*RedactOptions_BytesMask) isRedactOptions_MaskValue() {}

func (*RedactOptions_EnumMask) isRedactOptions_MaskValue() {}

var file_kit_redact_v1_redact_proto_extTypes = []protoimpl.ExtensionInfo{
	{
		ExtendedType:  (*descriptorpb.FieldOptions)(nil),
		ExtensionType: (*RedactOptions)(nil),
		Field:         105000,
		Name:          "kit.redact.v1.redact",
		Tag:           "bytes,105000,opt,name=redact",
		Filename:      "kit/redact/v1/redact.proto",
	},
}

// Extension fields to descriptorpb.FieldOptions.
var (
	// optional kit.redact.v1.RedactOptions redact = 105000;
	E_Redact = &file_kit_redact_v1_redact_proto_extTypes[0]
)

var File_kit_redact_v1_redact_proto protoreflect.FileDescriptor

const file_kit_redact_v1_redact_proto_rawDesc = "" +
	"\n" +
	"\x1akit/redact/v1/redact.proto\x12\rkit.redact.v1\x1a google/protobuf/descriptor.proto\"\xf7\x01\n" +
	"\rRedactOptions\x12\x16\n" +
	"\x06redact\x18\x01 \x01(\bR\x06redact\x12!\n" +
	"\vstring_mask\x18\x02 \x01(\tH\x00R\n" +
	"stringMask\x12\x1b\n" +
	"\bint_mask\x18\x03 \x01(\x03H\x00R\aintMask\x12!\n" +
	"\vdouble_mask\x18\x04 \x01(\x01H\x00R\n" +
	"doubleMask\x12\x1d\n" +
	"\tbool_mask\x18\x05 \x01(\bH\x00R\bboolMask\x12\x1f\n" +
	"\n" +
	"bytes_mask\x18\x06 \x01(\tH\x00R\tbytesMask\x12\x1d\n" +
	"\tenum_mask\x18\a \x01(\x05H\x00R\benumMaskB\f\n" +
	"\n" +
	"mask_value:X\n" +
	"\x06redact\x12\x1d.google.protobuf.FieldOptions\x18\xa8\xb4\x06 \x01(\v2\x1c.kit.redact.v1.RedactOptionsR\x06redact\x88\x01\x01B:Z8github.com/crypto-zero/go-kit/proto/kit/redact/v1;redactb\x06proto3"

var (
	file_kit_redact_v1_redact_proto_rawDescOnce sync.Once
	file_kit_redact_v1_redact_proto_rawDescData []byte
)

func file_kit_redact_v1_redact_proto_rawDescGZIP() []byte {
	file_kit_redact_v1_redact_proto_rawDescOnce.Do(func() {
		file_kit_redact_v1_redact_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_kit_redact_v1_redact_proto_rawDesc), len(file_kit_redact_v1_redact_proto_rawDesc)))
	})
	return file_kit_redact_v1_redact_proto_rawDescData
}

var file_kit_redact_v1_redact_proto_msgTypes = make([]protoimpl.MessageInfo, 1)
var file_kit_redact_v1_redact_proto_goTypes = []any{
	(*RedactOptions)(nil),             // 0: kit.redact.v1.RedactOptions
	(*descriptorpb.FieldOptions)(nil), // 1: google.protobuf.FieldOptions
}
var file_kit_redact_v1_redact_proto_depIdxs = []int32{
	1, // 0: kit.redact.v1.redact:extendee -> google.protobuf.FieldOptions
	0, // 1: kit.redact.v1.redact:type_name -> kit.redact.v1.RedactOptions
	2, // [2:2] is the sub-list for method output_type
	2, // [2:2] is the sub-list for method input_type
	1, // [1:2] is the sub-list for extension type_name
	0, // [0:1] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_kit_redact_v1_redact_proto_init() }
func file_kit_redact_v1_redact_proto_init() {
	if File_kit_redact_v1_redact_proto != nil {
		return
	}
	file_kit_redact_v1_redact_proto_msgTypes[0].OneofWrappers = []any{
		(*RedactOptions_StringMask)(nil),
		(*RedactOptions_IntMask)(nil),
		(*RedactOptions_DoubleMask)(nil),
		(*RedactOptions_BoolMask)(nil),
		(*RedactOptions_BytesMask)(nil),
		(*RedactOptions_EnumMask)(nil),
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_kit_redact_v1_redact_proto_rawDesc), len(file_kit_redact_v1_redact_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   1,
			NumExtensions: 1,
			NumServices:   0,
		},
		GoTypes:           file_kit_redact_v1_redact_proto_goTypes,
		DependencyIndexes: file_kit_redact_v1_redact_proto_depIdxs,
		MessageInfos:      file_kit_redact_v1_redact_proto_msgTypes,
		ExtensionInfos:    file_kit_redact_v1_redact_proto_extTypes,
	}.Build()
	File_kit_redact_v1_redact_proto = out.File
	file_kit_redact_v1_redact_proto_goTypes = nil
	file_kit_redact_v1_redact_proto_depIdxs = nil
}
