// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        (unknown)
// source: kit/redact/v1/redact.proto

package redact

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	descriptorpb "google.golang.org/protobuf/types/descriptorpb"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type RedactOptions struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Redact        bool                   `protobuf:"varint,1,opt,name=redact,proto3" json:"redact,omitempty"`
	Mask          string                 `protobuf:"bytes,2,opt,name=mask,proto3" json:"mask,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *RedactOptions) Reset() {
	*x = RedactOptions{}
	mi := &file_kit_redact_v1_redact_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RedactOptions) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RedactOptions) ProtoMessage() {}

func (x *RedactOptions) ProtoReflect() protoreflect.Message {
	mi := &file_kit_redact_v1_redact_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RedactOptions.ProtoReflect.Descriptor instead.
func (*RedactOptions) Descriptor() ([]byte, []int) {
	return file_kit_redact_v1_redact_proto_rawDescGZIP(), []int{0}
}

func (x *RedactOptions) GetRedact() bool {
	if x != nil {
		return x.Redact
	}
	return false
}

func (x *RedactOptions) GetMask() string {
	if x != nil {
		return x.Mask
	}
	return ""
}

var file_kit_redact_v1_redact_proto_extTypes = []protoimpl.ExtensionInfo{
	{
		ExtendedType:  (*descriptorpb.FieldOptions)(nil),
		ExtensionType: (*RedactOptions)(nil),
		Field:         50000,
		Name:          "kit.redact.v1.redact",
		Tag:           "bytes,50000,opt,name=redact",
		Filename:      "kit/redact/v1/redact.proto",
	},
}

// Extension fields to descriptorpb.FieldOptions.
var (
	// optional kit.redact.v1.RedactOptions redact = 50000;
	E_Redact = &file_kit_redact_v1_redact_proto_extTypes[0]
)

var File_kit_redact_v1_redact_proto protoreflect.FileDescriptor

const file_kit_redact_v1_redact_proto_rawDesc = "" +
	"\n" +
	"\x1akit/redact/v1/redact.proto\x12\rkit.redact.v1\x1a google/protobuf/descriptor.proto\";\n" +
	"\rRedactOptions\x12\x16\n" +
	"\x06redact\x18\x01 \x01(\bR\x06redact\x12\x12\n" +
	"\x04mask\x18\x02 \x01(\tR\x04mask:X\n" +
	"\x06redact\x12\x1d.google.protobuf.FieldOptions\x18І\x03 \x01(\v2\x1c.kit.redact.v1.RedactOptionsR\x06redact\x88\x01\x01B:Z8github.com/crypto-zero/go-kit/proto/kit/redact/v1;redactb\x06proto3"

var (
	file_kit_redact_v1_redact_proto_rawDescOnce sync.Once
	file_kit_redact_v1_redact_proto_rawDescData []byte
)

func file_kit_redact_v1_redact_proto_rawDescGZIP() []byte {
	file_kit_redact_v1_redact_proto_rawDescOnce.Do(func() {
		file_kit_redact_v1_redact_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_kit_redact_v1_redact_proto_rawDesc), len(file_kit_redact_v1_redact_proto_rawDesc)))
	})
	return file_kit_redact_v1_redact_proto_rawDescData
}

var file_kit_redact_v1_redact_proto_msgTypes = make([]protoimpl.MessageInfo, 1)
var file_kit_redact_v1_redact_proto_goTypes = []any{
	(*RedactOptions)(nil),             // 0: kit.redact.v1.RedactOptions
	(*descriptorpb.FieldOptions)(nil), // 1: google.protobuf.FieldOptions
}
var file_kit_redact_v1_redact_proto_depIdxs = []int32{
	1, // 0: kit.redact.v1.redact:extendee -> google.protobuf.FieldOptions
	0, // 1: kit.redact.v1.redact:type_name -> kit.redact.v1.RedactOptions
	2, // [2:2] is the sub-list for method output_type
	2, // [2:2] is the sub-list for method input_type
	1, // [1:2] is the sub-list for extension type_name
	0, // [0:1] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_kit_redact_v1_redact_proto_init() }
func file_kit_redact_v1_redact_proto_init() {
	if File_kit_redact_v1_redact_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_kit_redact_v1_redact_proto_rawDesc), len(file_kit_redact_v1_redact_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   1,
			NumExtensions: 1,
			NumServices:   0,
		},
		GoTypes:           file_kit_redact_v1_redact_proto_goTypes,
		DependencyIndexes: file_kit_redact_v1_redact_proto_depIdxs,
		MessageInfos:      file_kit_redact_v1_redact_proto_msgTypes,
		ExtensionInfos:    file_kit_redact_v1_redact_proto_extTypes,
	}.Build()
	File_kit_redact_v1_redact_proto = out.File
	file_kit_redact_v1_redact_proto_goTypes = nil
	file_kit_redact_v1_redact_proto_depIdxs = nil
}
