// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        (unknown)
// source: kit/auth/v1/auth.proto

package authv1

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	descriptorpb "google.golang.org/protobuf/types/descriptorpb"
	reflect "reflect"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

var file_kit_auth_v1_auth_proto_extTypes = []protoimpl.ExtensionInfo{
	{
		ExtendedType:  (*descriptorpb.MethodOptions)(nil),
		ExtensionType: (*bool)(nil),
		Field:         105001,
		Name:          "kit.auth.v1.public",
		Tag:           "varint,105001,opt,name=public",
		Filename:      "kit/auth/v1/auth.proto",
	},
}

// Extension fields to descriptorpb.MethodOptions.
var (
	// public marks an RPC operation as not requiring authenticated user context.
	//
	// optional bool public = 105001;
	E_Public = &file_kit_auth_v1_auth_proto_extTypes[0]
)

var File_kit_auth_v1_auth_proto protoreflect.FileDescriptor

const file_kit_auth_v1_auth_proto_rawDesc = "" +
	"\n" +
	"\x16kit/auth/v1/auth.proto\x12\vkit.auth.v1\x1a google/protobuf/descriptor.proto:8\n" +
	"\x06public\x12\x1e.google.protobuf.MethodOptions\x18\xa9\xb4\x06 \x01(\bR\x06publicB8Z6github.com/crypto-zero/go-kit/proto/kit/auth/v1;authv1b\x06proto3"

var file_kit_auth_v1_auth_proto_goTypes = []any{
	(*descriptorpb.MethodOptions)(nil), // 0: google.protobuf.MethodOptions
}
var file_kit_auth_v1_auth_proto_depIdxs = []int32{
	0, // 0: kit.auth.v1.public:extendee -> google.protobuf.MethodOptions
	1, // [1:1] is the sub-list for method output_type
	1, // [1:1] is the sub-list for method input_type
	1, // [1:1] is the sub-list for extension type_name
	0, // [0:1] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_kit_auth_v1_auth_proto_init() }
func file_kit_auth_v1_auth_proto_init() {
	if File_kit_auth_v1_auth_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_kit_auth_v1_auth_proto_rawDesc), len(file_kit_auth_v1_auth_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   0,
			NumExtensions: 1,
			NumServices:   0,
		},
		GoTypes:           file_kit_auth_v1_auth_proto_goTypes,
		DependencyIndexes: file_kit_auth_v1_auth_proto_depIdxs,
		ExtensionInfos:    file_kit_auth_v1_auth_proto_extTypes,
	}.Build()
	File_kit_auth_v1_auth_proto = out.File
	file_kit_auth_v1_auth_proto_goTypes = nil
	file_kit_auth_v1_auth_proto_depIdxs = nil
}
