// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        v7.34.1
// source: proto/kit/ratelimit/v1/ratelimit.proto

package ratelimitv1

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	descriptorpb "google.golang.org/protobuf/types/descriptorpb"
	durationpb "google.golang.org/protobuf/types/known/durationpb"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type Key int32

const (
	Key_KEY_UNSPECIFIED         Key = 0
	Key_KEY_OPERATION           Key = 1
	Key_KEY_CLIENT_IP           Key = 2
	Key_KEY_OPERATION_CLIENT_IP Key = 3
)

// Enum value maps for Key.
var (
	Key_name = map[int32]string{
		0: "KEY_UNSPECIFIED",
		1: "KEY_OPERATION",
		2: "KEY_CLIENT_IP",
		3: "KEY_OPERATION_CLIENT_IP",
	}
	Key_value = map[string]int32{
		"KEY_UNSPECIFIED":         0,
		"KEY_OPERATION":           1,
		"KEY_CLIENT_IP":           2,
		"KEY_OPERATION_CLIENT_IP": 3,
	}
)

func (x Key) Enum() *Key {
	p := new(Key)
	*p = x
	return p
}

func (x Key) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (Key) Descriptor() protoreflect.EnumDescriptor {
	return file_proto_kit_ratelimit_v1_ratelimit_proto_enumTypes[0].Descriptor()
}

func (Key) Type() protoreflect.EnumType {
	return &file_proto_kit_ratelimit_v1_ratelimit_proto_enumTypes[0]
}

func (x Key) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use Key.Descriptor instead.
func (Key) EnumDescriptor() ([]byte, []int) {
	return file_proto_kit_ratelimit_v1_ratelimit_proto_rawDescGZIP(), []int{0}
}

type RateLimit struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// rate is the number of tokens replenished every per duration.
	Rate int32 `protobuf:"varint,1,opt,name=rate,proto3" json:"rate,omitempty"`
	// per is the refill window for rate tokens.
	Per *durationpb.Duration `protobuf:"bytes,2,opt,name=per,proto3" json:"per,omitempty"`
	// burst is the maximum number of tokens a key can accumulate.
	Burst int32 `protobuf:"varint,3,opt,name=burst,proto3" json:"burst,omitempty"`
	// key selects how requests are grouped into buckets.
	Key           Key `protobuf:"varint,4,opt,name=key,proto3,enum=kit.ratelimit.v1.Key" json:"key,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *RateLimit) Reset() {
	*x = RateLimit{}
	mi := &file_proto_kit_ratelimit_v1_ratelimit_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RateLimit) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RateLimit) ProtoMessage() {}

func (x *RateLimit) ProtoReflect() protoreflect.Message {
	mi := &file_proto_kit_ratelimit_v1_ratelimit_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RateLimit.ProtoReflect.Descriptor instead.
func (*RateLimit) Descriptor() ([]byte, []int) {
	return file_proto_kit_ratelimit_v1_ratelimit_proto_rawDescGZIP(), []int{0}
}

func (x *RateLimit) GetRate() int32 {
	if x != nil {
		return x.Rate
	}
	return 0
}

func (x *RateLimit) GetPer() *durationpb.Duration {
	if x != nil {
		return x.Per
	}
	return nil
}

func (x *RateLimit) GetBurst() int32 {
	if x != nil {
		return x.Burst
	}
	return 0
}

func (x *RateLimit) GetKey() Key {
	if x != nil {
		return x.Key
	}
	return Key_KEY_UNSPECIFIED
}

var file_proto_kit_ratelimit_v1_ratelimit_proto_extTypes = []protoimpl.ExtensionInfo{
	{
		ExtendedType:  (*descriptorpb.MethodOptions)(nil),
		ExtensionType: (*RateLimit)(nil),
		Field:         106001,
		Name:          "kit.ratelimit.v1.rate_limit",
		Tag:           "bytes,106001,opt,name=rate_limit",
		Filename:      "proto/kit/ratelimit/v1/ratelimit.proto",
	},
}

// Extension fields to descriptorpb.MethodOptions.
var (
	// rate_limit configures per-method rate limiting for Kratos middleware.
	//
	// optional kit.ratelimit.v1.RateLimit rate_limit = 106001;
	E_RateLimit = &file_proto_kit_ratelimit_v1_ratelimit_proto_extTypes[0]
)

var File_proto_kit_ratelimit_v1_ratelimit_proto protoreflect.FileDescriptor

const file_proto_kit_ratelimit_v1_ratelimit_proto_rawDesc = "" +
	"\n" +
	"&proto/kit/ratelimit/v1/ratelimit.proto\x12\x10kit.ratelimit.v1\x1a google/protobuf/descriptor.proto\x1a\x1egoogle/protobuf/duration.proto\"\x8b\x01\n" +
	"\tRateLimit\x12\x12\n" +
	"\x04rate\x18\x01 \x01(\x05R\x04rate\x12+\n" +
	"\x03per\x18\x02 \x01(\v2\x19.google.protobuf.DurationR\x03per\x12\x14\n" +
	"\x05burst\x18\x03 \x01(\x05R\x05burst\x12'\n" +
	"\x03key\x18\x04 \x01(\x0e2\x15.kit.ratelimit.v1.KeyR\x03key*]\n" +
	"\x03Key\x12\x13\n" +
	"\x0fKEY_UNSPECIFIED\x10\x00\x12\x11\n" +
	"\rKEY_OPERATION\x10\x01\x12\x11\n" +
	"\rKEY_CLIENT_IP\x10\x02\x12\x1b\n" +
	"\x17KEY_OPERATION_CLIENT_IP\x10\x03:\\\n" +
	"\n" +
	"rate_limit\x12\x1e.google.protobuf.MethodOptions\x18\x91\xbc\x06 \x01(\v2\x1b.kit.ratelimit.v1.RateLimitR\trateLimitBBZ@github.com/crypto-zero/go-kit/proto/kit/ratelimit/v1;ratelimitv1b\x06proto3"

var (
	file_proto_kit_ratelimit_v1_ratelimit_proto_rawDescOnce sync.Once
	file_proto_kit_ratelimit_v1_ratelimit_proto_rawDescData []byte
)

func file_proto_kit_ratelimit_v1_ratelimit_proto_rawDescGZIP() []byte {
	file_proto_kit_ratelimit_v1_ratelimit_proto_rawDescOnce.Do(func() {
		file_proto_kit_ratelimit_v1_ratelimit_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_proto_kit_ratelimit_v1_ratelimit_proto_rawDesc), len(file_proto_kit_ratelimit_v1_ratelimit_proto_rawDesc)))
	})
	return file_proto_kit_ratelimit_v1_ratelimit_proto_rawDescData
}

var file_proto_kit_ratelimit_v1_ratelimit_proto_enumTypes = make([]protoimpl.EnumInfo, 1)
var file_proto_kit_ratelimit_v1_ratelimit_proto_msgTypes = make([]protoimpl.MessageInfo, 1)
var file_proto_kit_ratelimit_v1_ratelimit_proto_goTypes = []any{
	(Key)(0),                           // 0: kit.ratelimit.v1.Key
	(*RateLimit)(nil),                  // 1: kit.ratelimit.v1.RateLimit
	(*durationpb.Duration)(nil),        // 2: google.protobuf.Duration
	(*descriptorpb.MethodOptions)(nil), // 3: google.protobuf.MethodOptions
}
var file_proto_kit_ratelimit_v1_ratelimit_proto_depIdxs = []int32{
	2, // 0: kit.ratelimit.v1.RateLimit.per:type_name -> google.protobuf.Duration
	0, // 1: kit.ratelimit.v1.RateLimit.key:type_name -> kit.ratelimit.v1.Key
	3, // 2: kit.ratelimit.v1.rate_limit:extendee -> google.protobuf.MethodOptions
	1, // 3: kit.ratelimit.v1.rate_limit:type_name -> kit.ratelimit.v1.RateLimit
	4, // [4:4] is the sub-list for method output_type
	4, // [4:4] is the sub-list for method input_type
	3, // [3:4] is the sub-list for extension type_name
	2, // [2:3] is the sub-list for extension extendee
	0, // [0:2] is the sub-list for field type_name
}

func init() { file_proto_kit_ratelimit_v1_ratelimit_proto_init() }
func file_proto_kit_ratelimit_v1_ratelimit_proto_init() {
	if File_proto_kit_ratelimit_v1_ratelimit_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_proto_kit_ratelimit_v1_ratelimit_proto_rawDesc), len(file_proto_kit_ratelimit_v1_ratelimit_proto_rawDesc)),
			NumEnums:      1,
			NumMessages:   1,
			NumExtensions: 1,
			NumServices:   0,
		},
		GoTypes:           file_proto_kit_ratelimit_v1_ratelimit_proto_goTypes,
		DependencyIndexes: file_proto_kit_ratelimit_v1_ratelimit_proto_depIdxs,
		EnumInfos:         file_proto_kit_ratelimit_v1_ratelimit_proto_enumTypes,
		MessageInfos:      file_proto_kit_ratelimit_v1_ratelimit_proto_msgTypes,
		ExtensionInfos:    file_proto_kit_ratelimit_v1_ratelimit_proto_extTypes,
	}.Build()
	File_proto_kit_ratelimit_v1_ratelimit_proto = out.File
	file_proto_kit_ratelimit_v1_ratelimit_proto_goTypes = nil
	file_proto_kit_ratelimit_v1_ratelimit_proto_depIdxs = nil
}
