// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        (unknown)
// source: kit/sse/v1/sse.proto

package ssev1

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	descriptorpb "google.golang.org/protobuf/types/descriptorpb"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type StreamRule struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Types that are valid to be assigned to Pattern:
	//
	//	*StreamRule_Get
	//	*StreamRule_Post
	Pattern       isStreamRule_Pattern `protobuf_oneof:"pattern"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *StreamRule) Reset() {
	*x = StreamRule{}
	mi := &file_kit_sse_v1_sse_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *StreamRule) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*StreamRule) ProtoMessage() {}

func (x *StreamRule) ProtoReflect() protoreflect.Message {
	mi := &file_kit_sse_v1_sse_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use StreamRule.ProtoReflect.Descriptor instead.
func (*StreamRule) Descriptor() ([]byte, []int) {
	return file_kit_sse_v1_sse_proto_rawDescGZIP(), []int{0}
}

func (x *StreamRule) GetPattern() isStreamRule_Pattern {
	if x != nil {
		return x.Pattern
	}
	return nil
}

func (x *StreamRule) GetGet() string {
	if x != nil {
		if x, ok := x.Pattern.(*StreamRule_Get); ok {
			return x.Get
		}
	}
	return ""
}

func (x *StreamRule) GetPost() string {
	if x != nil {
		if x, ok := x.Pattern.(*StreamRule_Post); ok {
			return x.Post
		}
	}
	return ""
}

type isStreamRule_Pattern interface {
	isStreamRule_Pattern()
}

type StreamRule_Get struct {
	Get string `protobuf:"bytes,1,opt,name=get,proto3,oneof"`
}

type StreamRule_Post struct {
	Post string `protobuf:"bytes,2,opt,name=post,proto3,oneof"`
}

func (*StreamRule_Get) isStreamRule_Pattern() {}

func (*StreamRule_Post) isStreamRule_Pattern() {}

var file_kit_sse_v1_sse_proto_extTypes = []protoimpl.ExtensionInfo{
	{
		ExtendedType:  (*descriptorpb.MethodOptions)(nil),
		ExtensionType: (*StreamRule)(nil),
		Field:         81001,
		Name:          "kit.sse.v1.server_sent_event",
		Tag:           "bytes,81001,opt,name=server_sent_event",
		Filename:      "kit/sse/v1/sse.proto",
	},
}

// Extension fields to descriptorpb.MethodOptions.
var (
	// optional kit.sse.v1.StreamRule server_sent_event = 81001;
	E_ServerSentEvent = &file_kit_sse_v1_sse_proto_extTypes[0]
)

var File_kit_sse_v1_sse_proto protoreflect.FileDescriptor

const file_kit_sse_v1_sse_proto_rawDesc = "" +
	"\n" +
	"\x14kit/sse/v1/sse.proto\x12\n" +
	"kit.sse.v1\x1a google/protobuf/descriptor.proto\"A\n" +
	"\n" +
	"StreamRule\x12\x12\n" +
	"\x03get\x18\x01 \x01(\tH\x00R\x03get\x12\x14\n" +
	"\x04post\x18\x02 \x01(\tH\x00R\x04postB\t\n" +
	"\apattern:d\n" +
	"\x11server_sent_event\x12\x1e.google.protobuf.MethodOptions\x18\xe9\xf8\x04 \x01(\v2\x16.kit.sse.v1.StreamRuleR\x0fserverSentEventB6Z4github.com/crypto-zero/go-kit/proto/kit/sse/v1;ssev1b\x06proto3"

var (
	file_kit_sse_v1_sse_proto_rawDescOnce sync.Once
	file_kit_sse_v1_sse_proto_rawDescData []byte
)

func file_kit_sse_v1_sse_proto_rawDescGZIP() []byte {
	file_kit_sse_v1_sse_proto_rawDescOnce.Do(func() {
		file_kit_sse_v1_sse_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_kit_sse_v1_sse_proto_rawDesc), len(file_kit_sse_v1_sse_proto_rawDesc)))
	})
	return file_kit_sse_v1_sse_proto_rawDescData
}

var file_kit_sse_v1_sse_proto_msgTypes = make([]protoimpl.MessageInfo, 1)
var file_kit_sse_v1_sse_proto_goTypes = []any{
	(*StreamRule)(nil),                 // 0: kit.sse.v1.StreamRule
	(*descriptorpb.MethodOptions)(nil), // 1: google.protobuf.MethodOptions
}
var file_kit_sse_v1_sse_proto_depIdxs = []int32{
	1, // 0: kit.sse.v1.server_sent_event:extendee -> google.protobuf.MethodOptions
	0, // 1: kit.sse.v1.server_sent_event:type_name -> kit.sse.v1.StreamRule
	2, // [2:2] is the sub-list for method output_type
	2, // [2:2] is the sub-list for method input_type
	1, // [1:2] is the sub-list for extension type_name
	0, // [0:1] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_kit_sse_v1_sse_proto_init() }
func file_kit_sse_v1_sse_proto_init() {
	if File_kit_sse_v1_sse_proto != nil {
		return
	}
	file_kit_sse_v1_sse_proto_msgTypes[0].OneofWrappers = []any{
		(*StreamRule_Get)(nil),
		(*StreamRule_Post)(nil),
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_kit_sse_v1_sse_proto_rawDesc), len(file_kit_sse_v1_sse_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   1,
			NumExtensions: 1,
			NumServices:   0,
		},
		GoTypes:           file_kit_sse_v1_sse_proto_goTypes,
		DependencyIndexes: file_kit_sse_v1_sse_proto_depIdxs,
		MessageInfos:      file_kit_sse_v1_sse_proto_msgTypes,
		ExtensionInfos:    file_kit_sse_v1_sse_proto_extTypes,
	}.Build()
	File_kit_sse_v1_sse_proto = out.File
	file_kit_sse_v1_sse_proto_goTypes = nil
	file_kit_sse_v1_sse_proto_depIdxs = nil
}
