// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        (unknown)
// source: kit/errors/v1/error_reason.proto

package errors

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	descriptorpb "google.golang.org/protobuf/types/descriptorpb"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// general error codes: 190000 - 199999
type GeneralErrorReason int32

const (
	// unspecified error
	GeneralErrorReason_GENERAL_ERROR_REASON_UNSPECIFIED GeneralErrorReason = 0
	// no permission
	GeneralErrorReason_GENERAL_ERROR_REASON_NO_PERMISSION GeneralErrorReason = 190001
	// attempt later
	GeneralErrorReason_GENERAL_ERROR_REASON_ATTEMPT_LATER GeneralErrorReason = 190002
	// request not valid
	GeneralErrorReason_GENERAL_ERROR_REASON_REQUEST_NOT_VALID GeneralErrorReason = 190003
)

// Enum value maps for GeneralErrorReason.
var (
	GeneralErrorReason_name = map[int32]string{
		0:      "GENERAL_ERROR_REASON_UNSPECIFIED",
		190001: "GENERAL_ERROR_REASON_NO_PERMISSION",
		190002: "GENERAL_ERROR_REASON_ATTEMPT_LATER",
		190003: "GENERAL_ERROR_REASON_REQUEST_NOT_VALID",
	}
	GeneralErrorReason_value = map[string]int32{
		"GENERAL_ERROR_REASON_UNSPECIFIED":       0,
		"GENERAL_ERROR_REASON_NO_PERMISSION":     190001,
		"GENERAL_ERROR_REASON_ATTEMPT_LATER":     190002,
		"GENERAL_ERROR_REASON_REQUEST_NOT_VALID": 190003,
	}
)

func (x GeneralErrorReason) Enum() *GeneralErrorReason {
	p := new(GeneralErrorReason)
	*p = x
	return p
}

func (x GeneralErrorReason) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (GeneralErrorReason) Descriptor() protoreflect.EnumDescriptor {
	return file_kit_errors_v1_error_reason_proto_enumTypes[0].Descriptor()
}

func (GeneralErrorReason) Type() protoreflect.EnumType {
	return &file_kit_errors_v1_error_reason_proto_enumTypes[0]
}

func (x GeneralErrorReason) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use GeneralErrorReason.Descriptor instead.
func (GeneralErrorReason) EnumDescriptor() ([]byte, []int) {
	return file_kit_errors_v1_error_reason_proto_rawDescGZIP(), []int{0}
}

type EnumErrorDetail_Code int32

const (
	// unspecified error code 0
	EnumErrorDetail_CODE_UNSPECIFIED EnumErrorDetail_Code = 0
	// bad request status code 400
	EnumErrorDetail_CODE_BAD_REQUEST EnumErrorDetail_Code = 400
	// unauthorized status code 401
	EnumErrorDetail_CODE_UNAUTHORIZED EnumErrorDetail_Code = 401
	// forbidden status code 403
	EnumErrorDetail_CODE_FORBIDDEN EnumErrorDetail_Code = 403
	// not found status code 404
	EnumErrorDetail_CODE_NOT_FOUND EnumErrorDetail_Code = 404
	// conflict status code 409
	EnumErrorDetail_CODE_CONFLICT EnumErrorDetail_Code = 409
	// precondition failed status code 412
	EnumErrorDetail_CODE_PRECONDITION_FAILED EnumErrorDetail_Code = 412
	// range not satisfiable status code 416
	EnumErrorDetail_CODE_RANGE_NOT_SATISFIABLE EnumErrorDetail_Code = 416
	// too many requests status code 429
	EnumErrorDetail_CODE_TOO_MANY_REQUESTS EnumErrorDetail_Code = 429
	// client closed request status code 499
	EnumErrorDetail_CODE_CLIENT_CLOSED_REQUEST EnumErrorDetail_Code = 499
	// internal server error status code 500
	EnumErrorDetail_CODE_INTERNAL_SERVER_ERROR EnumErrorDetail_Code = 500
	// service unavailable status code 503
	EnumErrorDetail_CODE_SERVICE_UNAVAILABLE EnumErrorDetail_Code = 503
	// gateway timeout status code 504
	EnumErrorDetail_CODE_GATEWAY_TIMEOUT EnumErrorDetail_Code = 504
)

// Enum value maps for EnumErrorDetail_Code.
var (
	EnumErrorDetail_Code_name = map[int32]string{
		0:   "CODE_UNSPECIFIED",
		400: "CODE_BAD_REQUEST",
		401: "CODE_UNAUTHORIZED",
		403: "CODE_FORBIDDEN",
		404: "CODE_NOT_FOUND",
		409: "CODE_CONFLICT",
		412: "CODE_PRECONDITION_FAILED",
		416: "CODE_RANGE_NOT_SATISFIABLE",
		429: "CODE_TOO_MANY_REQUESTS",
		499: "CODE_CLIENT_CLOSED_REQUEST",
		500: "CODE_INTERNAL_SERVER_ERROR",
		503: "CODE_SERVICE_UNAVAILABLE",
		504: "CODE_GATEWAY_TIMEOUT",
	}
	EnumErrorDetail_Code_value = map[string]int32{
		"CODE_UNSPECIFIED":           0,
		"CODE_BAD_REQUEST":           400,
		"CODE_UNAUTHORIZED":          401,
		"CODE_FORBIDDEN":             403,
		"CODE_NOT_FOUND":             404,
		"CODE_CONFLICT":              409,
		"CODE_PRECONDITION_FAILED":   412,
		"CODE_RANGE_NOT_SATISFIABLE": 416,
		"CODE_TOO_MANY_REQUESTS":     429,
		"CODE_CLIENT_CLOSED_REQUEST": 499,
		"CODE_INTERNAL_SERVER_ERROR": 500,
		"CODE_SERVICE_UNAVAILABLE":   503,
		"CODE_GATEWAY_TIMEOUT":       504,
	}
)

func (x EnumErrorDetail_Code) Enum() *EnumErrorDetail_Code {
	p := new(EnumErrorDetail_Code)
	*p = x
	return p
}

func (x EnumErrorDetail_Code) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (EnumErrorDetail_Code) Descriptor() protoreflect.EnumDescriptor {
	return file_kit_errors_v1_error_reason_proto_enumTypes[1].Descriptor()
}

func (EnumErrorDetail_Code) Type() protoreflect.EnumType {
	return &file_kit_errors_v1_error_reason_proto_enumTypes[1]
}

func (x EnumErrorDetail_Code) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use EnumErrorDetail_Code.Descriptor instead.
func (EnumErrorDetail_Code) EnumDescriptor() ([]byte, []int) {
	return file_kit_errors_v1_error_reason_proto_rawDescGZIP(), []int{0, 0}
}

// for enum error code declaration
type EnumErrorDetail struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Message       string                 `protobuf:"bytes,1,opt,name=message,proto3" json:"message,omitempty"`
	Code          EnumErrorDetail_Code   `protobuf:"varint,2,opt,name=code,proto3,enum=kit.errors.v1.EnumErrorDetail_Code" json:"code,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *EnumErrorDetail) Reset() {
	*x = EnumErrorDetail{}
	mi := &file_kit_errors_v1_error_reason_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *EnumErrorDetail) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*EnumErrorDetail) ProtoMessage() {}

func (x *EnumErrorDetail) ProtoReflect() protoreflect.Message {
	mi := &file_kit_errors_v1_error_reason_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use EnumErrorDetail.ProtoReflect.Descriptor instead.
func (*EnumErrorDetail) Descriptor() ([]byte, []int) {
	return file_kit_errors_v1_error_reason_proto_rawDescGZIP(), []int{0}
}

func (x *EnumErrorDetail) GetMessage() string {
	if x != nil {
		return x.Message
	}
	return ""
}

func (x *EnumErrorDetail) GetCode() EnumErrorDetail_Code {
	if x != nil {
		return x.Code
	}
	return EnumErrorDetail_CODE_UNSPECIFIED
}

var file_kit_errors_v1_error_reason_proto_extTypes = []protoimpl.ExtensionInfo{
	{
		ExtendedType:  (*descriptorpb.EnumValueOptions)(nil),
		ExtensionType: (*EnumErrorDetail)(nil),
		Field:         1276,
		Name:          "kit.errors.v1.error_detail",
		Tag:           "bytes,1276,opt,name=error_detail",
		Filename:      "kit/errors/v1/error_reason.proto",
	},
}

// Extension fields to descriptorpb.EnumValueOptions.
var (
	// optional kit.errors.v1.EnumErrorDetail error_detail = 1276;
	E_ErrorDetail = &file_kit_errors_v1_error_reason_proto_extTypes[0]
)

var File_kit_errors_v1_error_reason_proto protoreflect.FileDescriptor

const file_kit_errors_v1_error_reason_proto_rawDesc = "" +
	"\n" +
	" kit/errors/v1/error_reason.proto\x12\rkit.errors.v1\x1a google/protobuf/descriptor.proto\"\xc9\x03\n" +
	"\x0fEnumErrorDetail\x12\x18\n" +
	"\amessage\x18\x01 \x01(\tR\amessage\x127\n" +
	"\x04code\x18\x02 \x01(\x0e2#.kit.errors.v1.EnumErrorDetail.CodeR\x04code\"\xe2\x02\n" +
	"\x04Code\x12\x14\n" +
	"\x10CODE_UNSPECIFIED\x10\x00\x12\x15\n" +
	"\x10CODE_BAD_REQUEST\x10\x90\x03\x12\x16\n" +
	"\x11CODE_UNAUTHORIZED\x10\x91\x03\x12\x13\n" +
	"\x0eCODE_FORBIDDEN\x10\x93\x03\x12\x13\n" +
	"\x0eCODE_NOT_FOUND\x10\x94\x03\x12\x12\n" +
	"\rCODE_CONFLICT\x10\x99\x03\x12\x1d\n" +
	"\x18CODE_PRECONDITION_FAILED\x10\x9c\x03\x12\x1f\n" +
	"\x1aCODE_RANGE_NOT_SATISFIABLE\x10\xa0\x03\x12\x1b\n" +
	"\x16CODE_TOO_MANY_REQUESTS\x10\xad\x03\x12\x1f\n" +
	"\x1aCODE_CLIENT_CLOSED_REQUEST\x10\xf3\x03\x12\x1f\n" +
	"\x1aCODE_INTERNAL_SERVER_ERROR\x10\xf4\x03\x12\x1d\n" +
	"\x18CODE_SERVICE_UNAVAILABLE\x10\xf7\x03\x12\x19\n" +
	"\x14CODE_GATEWAY_TIMEOUT\x10\xf8\x03*\x9d\x02\n" +
	"\x12GeneralErrorReason\x12<\n" +
	" GENERAL_ERROR_REASON_UNSPECIFIED\x10\x00\x1a\x16\xe2O\x13\n" +
	"\x11unspecified error\x12?\n" +
	"\"GENERAL_ERROR_REASON_NO_PERMISSION\x10\xb1\xcc\v\x1a\x15\xe2O\x12\n" +
	"\rno permission\x10\x93\x03\x12?\n" +
	"\"GENERAL_ERROR_REASON_ATTEMPT_LATER\x10\xb2\xcc\v\x1a\x15\xe2O\x12\n" +
	"\rattempt later\x10\x9c\x03\x12G\n" +
	"&GENERAL_ERROR_REASON_REQUEST_NOT_VALID\x10\xb3\xcc\v\x1a\x19\xe2O\x16\n" +
	"\x11request not valid\x10\x90\x03:e\n" +
	"\ferror_detail\x12!.google.protobuf.EnumValueOptions\x18\xfc\t \x01(\v2\x1e.kit.errors.v1.EnumErrorDetailR\verrorDetailB-Z+github.com/crypto-zero/go-kit/errors;errorsb\x06proto3"

var (
	file_kit_errors_v1_error_reason_proto_rawDescOnce sync.Once
	file_kit_errors_v1_error_reason_proto_rawDescData []byte
)

func file_kit_errors_v1_error_reason_proto_rawDescGZIP() []byte {
	file_kit_errors_v1_error_reason_proto_rawDescOnce.Do(func() {
		file_kit_errors_v1_error_reason_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_kit_errors_v1_error_reason_proto_rawDesc), len(file_kit_errors_v1_error_reason_proto_rawDesc)))
	})
	return file_kit_errors_v1_error_reason_proto_rawDescData
}

var file_kit_errors_v1_error_reason_proto_enumTypes = make([]protoimpl.EnumInfo, 2)
var file_kit_errors_v1_error_reason_proto_msgTypes = make([]protoimpl.MessageInfo, 1)
var file_kit_errors_v1_error_reason_proto_goTypes = []any{
	(GeneralErrorReason)(0),               // 0: kit.errors.v1.GeneralErrorReason
	(EnumErrorDetail_Code)(0),             // 1: kit.errors.v1.EnumErrorDetail.Code
	(*EnumErrorDetail)(nil),               // 2: kit.errors.v1.EnumErrorDetail
	(*descriptorpb.EnumValueOptions)(nil), // 3: google.protobuf.EnumValueOptions
}
var file_kit_errors_v1_error_reason_proto_depIdxs = []int32{
	1, // 0: kit.errors.v1.EnumErrorDetail.code:type_name -> kit.errors.v1.EnumErrorDetail.Code
	3, // 1: kit.errors.v1.error_detail:extendee -> google.protobuf.EnumValueOptions
	2, // 2: kit.errors.v1.error_detail:type_name -> kit.errors.v1.EnumErrorDetail
	3, // [3:3] is the sub-list for method output_type
	3, // [3:3] is the sub-list for method input_type
	2, // [2:3] is the sub-list for extension type_name
	1, // [1:2] is the sub-list for extension extendee
	0, // [0:1] is the sub-list for field type_name
}

func init() { file_kit_errors_v1_error_reason_proto_init() }
func file_kit_errors_v1_error_reason_proto_init() {
	if File_kit_errors_v1_error_reason_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_kit_errors_v1_error_reason_proto_rawDesc), len(file_kit_errors_v1_error_reason_proto_rawDesc)),
			NumEnums:      2,
			NumMessages:   1,
			NumExtensions: 1,
			NumServices:   0,
		},
		GoTypes:           file_kit_errors_v1_error_reason_proto_goTypes,
		DependencyIndexes: file_kit_errors_v1_error_reason_proto_depIdxs,
		EnumInfos:         file_kit_errors_v1_error_reason_proto_enumTypes,
		MessageInfos:      file_kit_errors_v1_error_reason_proto_msgTypes,
		ExtensionInfos:    file_kit_errors_v1_error_reason_proto_extTypes,
	}.Build()
	File_kit_errors_v1_error_reason_proto = out.File
	file_kit_errors_v1_error_reason_proto_goTypes = nil
	file_kit_errors_v1_error_reason_proto_depIdxs = nil
}
