// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        (unknown)
// source: kit/query/v1/query.proto

package query

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	timestamppb "google.golang.org/protobuf/types/known/timestamppb"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// TimeRange is a range of time.
type TimeRange struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// begin is the beginning of the range.
	Begin *timestamppb.Timestamp `protobuf:"bytes,1,opt,name=begin,proto3" json:"begin,omitempty"`
	// end is the end of the range.
	End           *timestamppb.Timestamp `protobuf:"bytes,2,opt,name=end,proto3" json:"end,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *TimeRange) Reset() {
	*x = TimeRange{}
	mi := &file_kit_query_v1_query_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *TimeRange) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*TimeRange) ProtoMessage() {}

func (x *TimeRange) ProtoReflect() protoreflect.Message {
	mi := &file_kit_query_v1_query_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use TimeRange.ProtoReflect.Descriptor instead.
func (*TimeRange) Descriptor() ([]byte, []int) {
	return file_kit_query_v1_query_proto_rawDescGZIP(), []int{0}
}

func (x *TimeRange) GetBegin() *timestamppb.Timestamp {
	if x != nil {
		return x.Begin
	}
	return nil
}

func (x *TimeRange) GetEnd() *timestamppb.Timestamp {
	if x != nil {
		return x.End
	}
	return nil
}

var File_kit_query_v1_query_proto protoreflect.FileDescriptor

const file_kit_query_v1_query_proto_rawDesc = "" +
	"\n" +
	"\x18kit/query/v1/query.proto\x12\fkit.query.v1\x1a\x1fgoogle/protobuf/timestamp.proto\"k\n" +
	"\tTimeRange\x120\n" +
	"\x05begin\x18\x01 \x01(\v2\x1a.google.protobuf.TimestampR\x05begin\x12,\n" +
	"\x03end\x18\x02 \x01(\v2\x1a.google.protobuf.TimestampR\x03endB8Z6github.com/crypto-zero/go-kit/proto/kit/query/v1;queryb\x06proto3"

var (
	file_kit_query_v1_query_proto_rawDescOnce sync.Once
	file_kit_query_v1_query_proto_rawDescData []byte
)

func file_kit_query_v1_query_proto_rawDescGZIP() []byte {
	file_kit_query_v1_query_proto_rawDescOnce.Do(func() {
		file_kit_query_v1_query_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_kit_query_v1_query_proto_rawDesc), len(file_kit_query_v1_query_proto_rawDesc)))
	})
	return file_kit_query_v1_query_proto_rawDescData
}

var file_kit_query_v1_query_proto_msgTypes = make([]protoimpl.MessageInfo, 1)
var file_kit_query_v1_query_proto_goTypes = []any{
	(*TimeRange)(nil),             // 0: kit.query.v1.TimeRange
	(*timestamppb.Timestamp)(nil), // 1: google.protobuf.Timestamp
}
var file_kit_query_v1_query_proto_depIdxs = []int32{
	1, // 0: kit.query.v1.TimeRange.begin:type_name -> google.protobuf.Timestamp
	1, // 1: kit.query.v1.TimeRange.end:type_name -> google.protobuf.Timestamp
	2, // [2:2] is the sub-list for method output_type
	2, // [2:2] is the sub-list for method input_type
	2, // [2:2] is the sub-list for extension type_name
	2, // [2:2] is the sub-list for extension extendee
	0, // [0:2] is the sub-list for field type_name
}

func init() { file_kit_query_v1_query_proto_init() }
func file_kit_query_v1_query_proto_init() {
	if File_kit_query_v1_query_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_kit_query_v1_query_proto_rawDesc), len(file_kit_query_v1_query_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   1,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_kit_query_v1_query_proto_goTypes,
		DependencyIndexes: file_kit_query_v1_query_proto_depIdxs,
		MessageInfos:      file_kit_query_v1_query_proto_msgTypes,
	}.Build()
	File_kit_query_v1_query_proto = out.File
	file_kit_query_v1_query_proto_goTypes = nil
	file_kit_query_v1_query_proto_depIdxs = nil
}
