// Code generated by ent, DO NOT EDIT.

package ent_crypto

import (
	"time"

	"github.com/crypto-zero/go-kit/ent_crypto/example"
	"github.com/crypto-zero/go-kit/ent_crypto/schema"
)

// The init function reads all schema descriptors with runtime code
// (default values, validators, hooks and policies) and stitches it
// to their package variables.
func init() {
	exampleFields := schema.Example{}.Fields()
	_ = exampleFields
	// exampleDescUsername is the schema descriptor for username field.
	exampleDescUsername := exampleFields[0].Descriptor()
	// example.UsernameValidator is a validator for the "username" field. It is called by the builders before save.
	example.UsernameValidator = exampleDescUsername.Validators[0].(func(string) error)
	// exampleDescEmail is the schema descriptor for email field.
	exampleDescEmail := exampleFields[1].Descriptor()
	// example.EmailValidator is a validator for the "email" field. It is called by the builders before save.
	example.EmailValidator = exampleDescEmail.Validators[0].(func(string) error)
	// exampleDescPassword is the schema descriptor for password field.
	exampleDescPassword := exampleFields[2].Descriptor()
	// example.PasswordValidator is a validator for the "password" field. It is called by the builders before save.
	example.PasswordValidator = exampleDescPassword.Validators[0].(func(string) error)
	// exampleDescCreatedAt is the schema descriptor for created_at field.
	exampleDescCreatedAt := exampleFields[3].Descriptor()
	// example.DefaultCreatedAt holds the default value on creation for the created_at field.
	example.DefaultCreatedAt = exampleDescCreatedAt.Default.(func() time.Time)
	// exampleDescUpdatedAt is the schema descriptor for updated_at field.
	exampleDescUpdatedAt := exampleFields[4].Descriptor()
	// example.DefaultUpdatedAt holds the default value on creation for the updated_at field.
	example.DefaultUpdatedAt = exampleDescUpdatedAt.Default.(func() time.Time)
}
