// Code generated by protoc-gen-go-redact. DO NOT EDIT.
// versions:
// - protoc-gen-go-redact v1.1.0
// - protoc             v6.33.2
// source: crossfile/container.proto

package crossfile

import (
	json "encoding/json"
	fmt "fmt"
	protojson "google.golang.org/protobuf/encoding/protojson"
)

func (x *Container) redact() map[string]any {
	if x == nil {
		return nil
	}
	m := make(map[string]any)
	m["containerId"] = x.ContainerId
	if x.Sensitive != nil {
		if r, ok := any(x.Sensitive).(interface{ redact() map[string]any }); ok {
			m["sensitive"] = r.redact()
		} else {
			m["sensitive"] = json.RawMessage(protojson.Format(x.Sensitive))
		}
	}
	return m
}

// Redact returns a redacted JSON string representation of Container.
// Sensitive fields are masked to prevent accidental logging of sensitive data.
// This method implements the Redacter interface for Kratos logging middleware.
func (x *Container) Redact() string {
	if x == nil {
		return "{}"
	}
	b, _ := json.Marshal(x.redact())
	return string(b)
}

func (x *ListContainer) redact() map[string]any {
	if x == nil {
		return nil
	}
	m := make(map[string]any)
	if len(x.Items) > 0 {
		items := make([]any, len(x.Items))
		for i, item := range x.Items {
			if item != nil {
				if r, ok := any(item).(interface{ redact() map[string]any }); ok {
					items[i] = r.redact()
				} else {
					items[i] = json.RawMessage(protojson.Format(item))
				}
			}
		}
		m["items"] = items
	}
	return m
}

// Redact returns a redacted JSON string representation of ListContainer.
// Sensitive fields are masked to prevent accidental logging of sensitive data.
// This method implements the Redacter interface for Kratos logging middleware.
func (x *ListContainer) Redact() string {
	if x == nil {
		return "{}"
	}
	b, _ := json.Marshal(x.redact())
	return string(b)
}

func (x *DeepContainer) redact() map[string]any {
	if x == nil {
		return nil
	}
	m := make(map[string]any)
	m["id"] = x.Id
	if x.Nested != nil {
		if r, ok := any(x.Nested).(interface{ redact() map[string]any }); ok {
			m["nested"] = r.redact()
		} else {
			m["nested"] = json.RawMessage(protojson.Format(x.Nested))
		}
	}
	return m
}

// Redact returns a redacted JSON string representation of DeepContainer.
// Sensitive fields are masked to prevent accidental logging of sensitive data.
// This method implements the Redacter interface for Kratos logging middleware.
func (x *DeepContainer) Redact() string {
	if x == nil {
		return "{}"
	}
	b, _ := json.Marshal(x.redact())
	return string(b)
}

func (x *MapContainer) redact() map[string]any {
	if x == nil {
		return nil
	}
	m := make(map[string]any)
	if len(x.DataMap) > 0 {
		mapVal := make(map[string]any)
		for k, v := range x.DataMap {
			key := fmt.Sprintf("%v", k)
			if v != nil {
				if r, ok := any(v).(interface{ redact() map[string]any }); ok {
					mapVal[key] = r.redact()
				} else {
					mapVal[key] = json.RawMessage(protojson.Format(v))
				}
			}
		}
		m["dataMap"] = mapVal
	}
	return m
}

// Redact returns a redacted JSON string representation of MapContainer.
// Sensitive fields are masked to prevent accidental logging of sensitive data.
// This method implements the Redacter interface for Kratos logging middleware.
func (x *MapContainer) Redact() string {
	if x == nil {
		return "{}"
	}
	b, _ := json.Marshal(x.redact())
	return string(b)
}
