// container.proto - Contains messages that reference sensitive.proto messages
// This file tests cross-file propagation of redact requirements

// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        v6.33.2
// source: crossfile/container.proto

package crossfile

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// Container references SensitiveData from another file
// It should get a Redact() method via cross-file propagation
type Container struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	ContainerId   string                 `protobuf:"bytes,1,opt,name=container_id,json=containerId,proto3" json:"container_id,omitempty"`
	Sensitive     *SensitiveData         `protobuf:"bytes,2,opt,name=sensitive,proto3" json:"sensitive,omitempty"` // Cross-file reference to message with redacted fields
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Container) Reset() {
	*x = Container{}
	mi := &file_crossfile_container_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Container) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Container) ProtoMessage() {}

func (x *Container) ProtoReflect() protoreflect.Message {
	mi := &file_crossfile_container_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Container.ProtoReflect.Descriptor instead.
func (*Container) Descriptor() ([]byte, []int) {
	return file_crossfile_container_proto_rawDescGZIP(), []int{0}
}

func (x *Container) GetContainerId() string {
	if x != nil {
		return x.ContainerId
	}
	return ""
}

func (x *Container) GetSensitive() *SensitiveData {
	if x != nil {
		return x.Sensitive
	}
	return nil
}

// ListContainer contains repeated cross-file references
type ListContainer struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Items         []*SensitiveData       `protobuf:"bytes,1,rep,name=items,proto3" json:"items,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListContainer) Reset() {
	*x = ListContainer{}
	mi := &file_crossfile_container_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListContainer) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListContainer) ProtoMessage() {}

func (x *ListContainer) ProtoReflect() protoreflect.Message {
	mi := &file_crossfile_container_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListContainer.ProtoReflect.Descriptor instead.
func (*ListContainer) Descriptor() ([]byte, []int) {
	return file_crossfile_container_proto_rawDescGZIP(), []int{1}
}

func (x *ListContainer) GetItems() []*SensitiveData {
	if x != nil {
		return x.Items
	}
	return nil
}

// DeepContainer has a nested reference through NestedSensitive
type DeepContainer struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	Nested        *NestedSensitive       `protobuf:"bytes,2,opt,name=nested,proto3" json:"nested,omitempty"` // NestedSensitive contains SensitiveData
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DeepContainer) Reset() {
	*x = DeepContainer{}
	mi := &file_crossfile_container_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DeepContainer) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DeepContainer) ProtoMessage() {}

func (x *DeepContainer) ProtoReflect() protoreflect.Message {
	mi := &file_crossfile_container_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DeepContainer.ProtoReflect.Descriptor instead.
func (*DeepContainer) Descriptor() ([]byte, []int) {
	return file_crossfile_container_proto_rawDescGZIP(), []int{2}
}

func (x *DeepContainer) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *DeepContainer) GetNested() *NestedSensitive {
	if x != nil {
		return x.Nested
	}
	return nil
}

// MapContainer has a map with cross-file message values
type MapContainer struct {
	state         protoimpl.MessageState    `protogen:"open.v1"`
	DataMap       map[string]*SensitiveData `protobuf:"bytes,1,rep,name=data_map,json=dataMap,proto3" json:"data_map,omitempty" protobuf_key:"bytes,1,opt,name=key" protobuf_val:"bytes,2,opt,name=value"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *MapContainer) Reset() {
	*x = MapContainer{}
	mi := &file_crossfile_container_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *MapContainer) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*MapContainer) ProtoMessage() {}

func (x *MapContainer) ProtoReflect() protoreflect.Message {
	mi := &file_crossfile_container_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use MapContainer.ProtoReflect.Descriptor instead.
func (*MapContainer) Descriptor() ([]byte, []int) {
	return file_crossfile_container_proto_rawDescGZIP(), []int{3}
}

func (x *MapContainer) GetDataMap() map[string]*SensitiveData {
	if x != nil {
		return x.DataMap
	}
	return nil
}

var File_crossfile_container_proto protoreflect.FileDescriptor

const file_crossfile_container_proto_rawDesc = "" +
	"\n" +
	"\x19crossfile/container.proto\x12\x12testdata.crossfile\x1a\x19crossfile/sensitive.proto\"o\n" +
	"\tContainer\x12!\n" +
	"\fcontainer_id\x18\x01 \x01(\tR\vcontainerId\x12?\n" +
	"\tsensitive\x18\x02 \x01(\v2!.testdata.crossfile.SensitiveDataR\tsensitive\"H\n" +
	"\rListContainer\x127\n" +
	"\x05items\x18\x01 \x03(\v2!.testdata.crossfile.SensitiveDataR\x05items\"\\\n" +
	"\rDeepContainer\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\x12;\n" +
	"\x06nested\x18\x02 \x01(\v2#.testdata.crossfile.NestedSensitiveR\x06nested\"\xb7\x01\n" +
	"\fMapContainer\x12H\n" +
	"\bdata_map\x18\x01 \x03(\v2-.testdata.crossfile.MapContainer.DataMapEntryR\adataMap\x1a]\n" +
	"\fDataMapEntry\x12\x10\n" +
	"\x03key\x18\x01 \x01(\tR\x03key\x127\n" +
	"\x05value\x18\x02 \x01(\v2!.testdata.crossfile.SensitiveDataR\x05value:\x028\x01B_Z]github.com/crypto-zero/go-kit/logging/protoc-gen-go-redact/internal/redact/testdata/crossfileb\x06proto3"

var (
	file_crossfile_container_proto_rawDescOnce sync.Once
	file_crossfile_container_proto_rawDescData []byte
)

func file_crossfile_container_proto_rawDescGZIP() []byte {
	file_crossfile_container_proto_rawDescOnce.Do(func() {
		file_crossfile_container_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_crossfile_container_proto_rawDesc), len(file_crossfile_container_proto_rawDesc)))
	})
	return file_crossfile_container_proto_rawDescData
}

var file_crossfile_container_proto_msgTypes = make([]protoimpl.MessageInfo, 5)
var file_crossfile_container_proto_goTypes = []any{
	(*Container)(nil),       // 0: testdata.crossfile.Container
	(*ListContainer)(nil),   // 1: testdata.crossfile.ListContainer
	(*DeepContainer)(nil),   // 2: testdata.crossfile.DeepContainer
	(*MapContainer)(nil),    // 3: testdata.crossfile.MapContainer
	nil,                     // 4: testdata.crossfile.MapContainer.DataMapEntry
	(*SensitiveData)(nil),   // 5: testdata.crossfile.SensitiveData
	(*NestedSensitive)(nil), // 6: testdata.crossfile.NestedSensitive
}
var file_crossfile_container_proto_depIdxs = []int32{
	5, // 0: testdata.crossfile.Container.sensitive:type_name -> testdata.crossfile.SensitiveData
	5, // 1: testdata.crossfile.ListContainer.items:type_name -> testdata.crossfile.SensitiveData
	6, // 2: testdata.crossfile.DeepContainer.nested:type_name -> testdata.crossfile.NestedSensitive
	4, // 3: testdata.crossfile.MapContainer.data_map:type_name -> testdata.crossfile.MapContainer.DataMapEntry
	5, // 4: testdata.crossfile.MapContainer.DataMapEntry.value:type_name -> testdata.crossfile.SensitiveData
	5, // [5:5] is the sub-list for method output_type
	5, // [5:5] is the sub-list for method input_type
	5, // [5:5] is the sub-list for extension type_name
	5, // [5:5] is the sub-list for extension extendee
	0, // [0:5] is the sub-list for field type_name
}

func init() { file_crossfile_container_proto_init() }
func file_crossfile_container_proto_init() {
	if File_crossfile_container_proto != nil {
		return
	}
	file_crossfile_sensitive_proto_init()
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_crossfile_container_proto_rawDesc), len(file_crossfile_container_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   5,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_crossfile_container_proto_goTypes,
		DependencyIndexes: file_crossfile_container_proto_depIdxs,
		MessageInfos:      file_crossfile_container_proto_msgTypes,
	}.Build()
	File_crossfile_container_proto = out.File
	file_crossfile_container_proto_goTypes = nil
	file_crossfile_container_proto_depIdxs = nil
}
