// sensitive.proto - Contains messages with directly marked redact fields

// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        v6.33.2
// source: crossfile/sensitive.proto

package crossfile

import (
	_ "github.com/crypto-zero/go-kit/proto/kit/redact/v1"
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// SensitiveData contains directly marked redact fields
type SensitiveData struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	Password      string                 `protobuf:"bytes,2,opt,name=password,proto3" json:"password,omitempty"`
	Phone         string                 `protobuf:"bytes,3,opt,name=phone,proto3" json:"phone,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SensitiveData) Reset() {
	*x = SensitiveData{}
	mi := &file_crossfile_sensitive_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SensitiveData) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SensitiveData) ProtoMessage() {}

func (x *SensitiveData) ProtoReflect() protoreflect.Message {
	mi := &file_crossfile_sensitive_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SensitiveData.ProtoReflect.Descriptor instead.
func (*SensitiveData) Descriptor() ([]byte, []int) {
	return file_crossfile_sensitive_proto_rawDescGZIP(), []int{0}
}

func (x *SensitiveData) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *SensitiveData) GetPassword() string {
	if x != nil {
		return x.Password
	}
	return ""
}

func (x *SensitiveData) GetPhone() string {
	if x != nil {
		return x.Phone
	}
	return ""
}

// NestedSensitive contains a nested message with sensitive data
type NestedSensitive struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Name          string                 `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
	Data          *SensitiveData         `protobuf:"bytes,2,opt,name=data,proto3" json:"data,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *NestedSensitive) Reset() {
	*x = NestedSensitive{}
	mi := &file_crossfile_sensitive_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *NestedSensitive) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*NestedSensitive) ProtoMessage() {}

func (x *NestedSensitive) ProtoReflect() protoreflect.Message {
	mi := &file_crossfile_sensitive_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use NestedSensitive.ProtoReflect.Descriptor instead.
func (*NestedSensitive) Descriptor() ([]byte, []int) {
	return file_crossfile_sensitive_proto_rawDescGZIP(), []int{1}
}

func (x *NestedSensitive) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *NestedSensitive) GetData() *SensitiveData {
	if x != nil {
		return x.Data
	}
	return nil
}

var File_crossfile_sensitive_proto protoreflect.FileDescriptor

const file_crossfile_sensitive_proto_rawDesc = "" +
	"\n" +
	"\x19crossfile/sensitive.proto\x12\x12testdata.crossfile\x1a\x1akit/redact/v1/redact.proto\"v\n" +
	"\rSensitiveData\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\x12.\n" +
	"\bpassword\x18\x02 \x01(\tB\x12¢3\x0e\b\x01\x12\n" +
	"[PASSWORD]R\bpassword\x12%\n" +
	"\x05phone\x18\x03 \x01(\tB\x0f¢3\v\b\x01\x12\a[PHONE]R\x05phone\"\\\n" +
	"\x0fNestedSensitive\x12\x12\n" +
	"\x04name\x18\x01 \x01(\tR\x04name\x125\n" +
	"\x04data\x18\x02 \x01(\v2!.testdata.crossfile.SensitiveDataR\x04dataB_Z]github.com/crypto-zero/go-kit/logging/protoc-gen-go-redact/internal/redact/testdata/crossfileb\x06proto3"

var (
	file_crossfile_sensitive_proto_rawDescOnce sync.Once
	file_crossfile_sensitive_proto_rawDescData []byte
)

func file_crossfile_sensitive_proto_rawDescGZIP() []byte {
	file_crossfile_sensitive_proto_rawDescOnce.Do(func() {
		file_crossfile_sensitive_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_crossfile_sensitive_proto_rawDesc), len(file_crossfile_sensitive_proto_rawDesc)))
	})
	return file_crossfile_sensitive_proto_rawDescData
}

var file_crossfile_sensitive_proto_msgTypes = make([]protoimpl.MessageInfo, 2)
var file_crossfile_sensitive_proto_goTypes = []any{
	(*SensitiveData)(nil),   // 0: testdata.crossfile.SensitiveData
	(*NestedSensitive)(nil), // 1: testdata.crossfile.NestedSensitive
}
var file_crossfile_sensitive_proto_depIdxs = []int32{
	0, // 0: testdata.crossfile.NestedSensitive.data:type_name -> testdata.crossfile.SensitiveData
	1, // [1:1] is the sub-list for method output_type
	1, // [1:1] is the sub-list for method input_type
	1, // [1:1] is the sub-list for extension type_name
	1, // [1:1] is the sub-list for extension extendee
	0, // [0:1] is the sub-list for field type_name
}

func init() { file_crossfile_sensitive_proto_init() }
func file_crossfile_sensitive_proto_init() {
	if File_crossfile_sensitive_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_crossfile_sensitive_proto_rawDesc), len(file_crossfile_sensitive_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   2,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_crossfile_sensitive_proto_goTypes,
		DependencyIndexes: file_crossfile_sensitive_proto_depIdxs,
		MessageInfos:      file_crossfile_sensitive_proto_msgTypes,
	}.Build()
	File_crossfile_sensitive_proto = out.File
	file_crossfile_sensitive_proto_goTypes = nil
	file_crossfile_sensitive_proto_depIdxs = nil
}
