// Code generated by protoc-gen-go-redact. DO NOT EDIT.
// versions:
// - protoc-gen-go-redact v1.1.0
// - protoc             v6.33.2
// source: crossfile/sensitive.proto

package crossfile

import (
	json "encoding/json"
	protojson "google.golang.org/protobuf/encoding/protojson"
)

func (x *SensitiveData) redact() map[string]any {
	if x == nil {
		return nil
	}
	m := make(map[string]any)
	m["id"] = x.Id
	m["password"] = "[PASSWORD]"
	m["phone"] = "[PHONE]"
	return m
}

// Redact returns a redacted JSON string representation of SensitiveData.
// Sensitive fields are masked to prevent accidental logging of sensitive data.
// This method implements the Redacter interface for Kratos logging middleware.
func (x *SensitiveData) Redact() string {
	if x == nil {
		return "{}"
	}
	b, _ := json.Marshal(x.redact())
	return string(b)
}

func (x *NestedSensitive) redact() map[string]any {
	if x == nil {
		return nil
	}
	m := make(map[string]any)
	m["name"] = x.Name
	if x.Data != nil {
		if r, ok := any(x.Data).(interface{ redact() map[string]any }); ok {
			m["data"] = r.redact()
		} else {
			m["data"] = json.RawMessage(protojson.Format(x.Data))
		}
	}
	return m
}

// Redact returns a redacted JSON string representation of NestedSensitive.
// Sensitive fields are masked to prevent accidental logging of sensitive data.
// This method implements the Redacter interface for Kratos logging middleware.
func (x *NestedSensitive) Redact() string {
	if x == nil {
		return "{}"
	}
	b, _ := json.Marshal(x.redact())
	return string(b)
}
