// Code generated by protoc-gen-go-redact. DO NOT EDIT.
// versions:
// - protoc-gen-go-redact v0.0.1
// - protoc             v5.29.3
// source: testdata/example.proto

package testdata

import (
	"google.golang.org/protobuf/encoding/protojson"
	"google.golang.org/protobuf/proto"
)

// Redact returns a redacted JSON string representation of User.
// Sensitive fields are masked to prevent accidental logging of sensitive data.
func (x *User) Redact() string {
	if x == nil {
		return "{}"
	}
	clone := proto.Clone(x).(*User)
	clone.Email = "***"
	clone.Password = "[HIDDEN]"
	b, _ := protojson.Marshal(clone)
	return string(b)
}

// Redact returns a redacted JSON string representation of Account.
// Sensitive fields are masked to prevent accidental logging of sensitive data.
func (x *Account) Redact() string {
	if x == nil {
		return "{}"
	}
	clone := proto.Clone(x).(*Account)
	clone.SecretKey = "***SECRET***"
	b, _ := protojson.Marshal(clone)
	return string(b)
}
