package main

import (
	"flag"
	"fmt"
	"strconv"
	"strings"

	ssev1 "github.com/crypto-zero/go-kit/proto/kit/sse/v1"
	"google.golang.org/genproto/googleapis/api/annotations"
	"google.golang.org/protobuf/compiler/protogen"
	"google.golang.org/protobuf/proto"
	"google.golang.org/protobuf/types/pluginpb"
)

const version = "v0.1.0"

var (
	contextPackage = protogen.GoImportPath("context")
	khttpPackage   = protogen.GoImportPath("github.com/go-kratos/kratos/v2/transport/http")
	ssePackage     = protogen.GoImportPath("github.com/crypto-zero/go-kit/sse")
	kratosPackage  = protogen.GoImportPath("github.com/crypto-zero/go-kit/sse/kratos")
)

func main() {
	var flags flag.FlagSet
	protogen.Options{ParamFunc: flags.Set}.Run(func(plugin *protogen.Plugin) error {
		plugin.SupportedFeatures = uint64(pluginpb.CodeGeneratorResponse_FEATURE_PROTO3_OPTIONAL)
		for _, file := range plugin.Files {
			if file.Generate {
				generateFile(plugin, file)
			}
		}
		return nil
	})
}

type sseMethod struct {
	service *protogen.Service
	method  *protogen.Method
	routes  []sseRoute
}

type sseRoute struct {
	verb string
	path string
}

func generateFile(plugin *protogen.Plugin, file *protogen.File) {
	methods := collectSSEMethods(file)
	if len(methods) == 0 {
		return
	}

	filename := file.GeneratedFilenamePrefix + "_sse.pb.go"
	g := plugin.NewGeneratedFile(filename, file.GoImportPath)
	g.P("// Code generated by protoc-gen-go-sse. DO NOT EDIT.")
	g.P("// versions:")
	g.P("// - protoc-gen-go-sse ", version)
	g.P("// - protoc             ", protocVersion(plugin))
	g.P("// source: ", file.Desc.Path())
	g.P()
	g.P("package ", file.GoPackageName)
	g.P()

	grouped := map[*protogen.Service][]sseMethod{}
	for _, m := range methods {
		grouped[m.service] = append(grouped[m.service], m)
	}
	for _, service := range file.Services {
		items := grouped[service]
		if len(items) == 0 {
			continue
		}
		genService(g, service, items)
	}
}

func collectSSEMethods(file *protogen.File) []sseMethod {
	var out []sseMethod
	for _, service := range file.Services {
		for _, method := range service.Methods {
			opts := method.Desc.Options()
			if !proto.HasExtension(opts, ssev1.E_ServerSentEvent) {
				continue
			}
			enabled, ok := proto.GetExtension(opts, ssev1.E_ServerSentEvent).(bool)
			if !ok || !enabled {
				continue
			}
			if !proto.HasExtension(opts, annotations.E_Http) {
				continue
			}
			rule, ok := proto.GetExtension(opts, annotations.E_Http).(*annotations.HttpRule)
			if !ok || rule == nil {
				continue
			}
			var routes []sseRoute
			for _, binding := range httpRuleBindings(rule) {
				verb, path := httpRuleHTTP(binding)
				if verb == "" || path == "" {
					continue
				}
				routes = append(routes, sseRoute{verb: verb, path: path})
			}
			if len(routes) == 0 {
				continue
			}
			out = append(out, sseMethod{service: service, method: method, routes: routes})
		}
	}
	return out
}

func httpRuleBindings(rule *annotations.HttpRule) []*annotations.HttpRule {
	out := []*annotations.HttpRule{rule}
	out = append(out, rule.GetAdditionalBindings()...)
	return out
}

func httpRuleHTTP(rule *annotations.HttpRule) (string, string) {
	switch pattern := rule.GetPattern().(type) {
	case *annotations.HttpRule_Get:
		return "GET", pattern.Get
	case *annotations.HttpRule_Put:
		return "PUT", pattern.Put
	case *annotations.HttpRule_Post:
		return "POST", pattern.Post
	case *annotations.HttpRule_Delete:
		return "DELETE", pattern.Delete
	case *annotations.HttpRule_Patch:
		return "PATCH", pattern.Patch
	case *annotations.HttpRule_Custom:
		return pattern.Custom.Kind, pattern.Custom.Path
	default:
		return "", ""
	}
}

func genService(g *protogen.GeneratedFile, service *protogen.Service, methods []sseMethod) {
	serviceName := service.GoName
	contextIdent := g.QualifiedGoIdent(contextPackage.Ident("Context"))
	streamIdent := g.QualifiedGoIdent(ssePackage.Ident("Stream"))
	readerIdent := g.QualifiedGoIdent(ssePackage.Ident("Reader"))
	serverIdent := g.QualifiedGoIdent(khttpPackage.Ident("Server"))
	optionIdent := g.QualifiedGoIdent(kratosPackage.Ident("HTTPStreamOption"))
	clientIdent := g.QualifiedGoIdent(kratosPackage.Ident("HTTPClient"))
	callOptionIdent := g.QualifiedGoIdent(kratosPackage.Ident("HTTPStreamCallOption"))

	g.P("type ", serviceName, "SSEServer interface {")
	for _, item := range methods {
		g.P(item.method.GoName, "(", contextIdent, ", *", item.method.Input.GoIdent, ", *", streamIdent, ") error")
	}
	g.P("}")
	g.P()

	g.P("func Register", serviceName, "SSEServer(s *", serverIdent, ", srv ", serviceName, "SSEServer, opts ...", optionIdent, ") {")
	for _, item := range methods {
		g.P("_", serviceName, "_", item.method.GoName, "_SSE_Register(s, srv, opts...)")
	}
	g.P("}")
	g.P()

	g.P("type ", serviceName, "SSEClient interface {")
	for _, item := range methods {
		g.P(item.method.GoName, "(", contextIdent, ", *", item.method.Input.GoIdent, ", ...", callOptionIdent, ") (*", readerIdent, ", error)")
	}
	g.P("}")
	g.P()

	g.P("type ", serviceName, "SSEClientImpl struct {")
	g.P("cc *", clientIdent)
	g.P("}")
	g.P()

	g.P("func New", serviceName, "SSEClient(client *", clientIdent, ") ", serviceName, "SSEClient {")
	g.P("return &", serviceName, "SSEClientImpl{client}")
	g.P("}")
	g.P()

	for _, item := range methods {
		genMethod(g, item)
	}
}

func genMethod(g *protogen.GeneratedFile, item sseMethod) {
	serviceName := item.service.GoName
	methodName := item.method.GoName
	operationConst := "Operation" + serviceName + methodName + "SSE"

	serverIdent := g.QualifiedGoIdent(khttpPackage.Ident("Server"))
	optionIdent := g.QualifiedGoIdent(kratosPackage.Ident("HTTPStreamOption"))
	registerIdent := g.QualifiedGoIdent(kratosPackage.Ident("RegisterHTTPStream"))

	g.P("const ", operationConst, ` = "/`, item.method.Desc.Parent().FullName(), `/`, item.method.Desc.Name(), `"`)
	g.P()
	g.P("func _", serviceName, "_", methodName, "_SSE_Register(s *", serverIdent, ", srv ", serviceName, "SSEServer, opts ...", optionIdent, ") {")
	for _, route := range item.routes {
		g.P(registerIdent, "(s, ", strconv.Quote(route.verb), ", ", strconv.Quote(route.path), ", ", operationConst, ", srv.", methodName, ", opts...)")
	}
	g.P("}")
	g.P()

	callOptionIdent := g.QualifiedGoIdent(kratosPackage.Ident("HTTPStreamCallOption"))
	readerIdent := g.QualifiedGoIdent(ssePackage.Ident("Reader"))
	bindingIdent := g.QualifiedGoIdent(protogen.GoImportPath("github.com/go-kratos/kratos/v2/transport/http/binding").Ident("EncodeURL"))
	route := item.routes[0]
	g.P("func (c *", serviceName, "SSEClientImpl) ", methodName, "(ctx ", g.QualifiedGoIdent(contextPackage.Ident("Context")), ", in *", item.method.Input.GoIdent, ", opts ...", callOptionIdent, ") (*", readerIdent, ", error) {")
	g.P("pattern := ", strconv.Quote(route.path))
	g.P("path := ", bindingIdent, "(pattern, in, true)")
	g.P("return c.cc.Open(ctx, ", strconv.Quote(route.verb), ", path, opts...)")
	g.P("}")
	g.P()
}

func protocVersion(plugin *protogen.Plugin) string {
	v := plugin.Request.GetCompilerVersion()
	if v == nil {
		return "(unknown)"
	}
	var suffix string
	if v.GetSuffix() != "" {
		suffix = "-" + v.GetSuffix()
	}
	return strings.TrimPrefix(fmt.Sprintf("v%d.%d.%d%s", v.GetMajor(), v.GetMinor(), v.GetPatch(), suffix), "v0.0.0")
}
