package main

import (
	"flag"
	"fmt"
	"net/http"
	"strconv"
	"strings"

	ssev1 "github.com/crypto-zero/go-kit/proto/kit/sse/v1"
	"google.golang.org/protobuf/compiler/protogen"
	"google.golang.org/protobuf/proto"
	"google.golang.org/protobuf/types/pluginpb"
)

const version = "v0.1.0"

var (
	contextPackage = protogen.GoImportPath("context")
	khttpPackage   = protogen.GoImportPath("github.com/go-kratos/kratos/v2/transport/http")
	ssePackage     = protogen.GoImportPath("github.com/crypto-zero/go-kit/sse")
	kratosPackage  = protogen.GoImportPath("github.com/crypto-zero/go-kit/sse/kratos")
)

func main() {
	var flags flag.FlagSet
	protogen.Options{ParamFunc: flags.Set}.Run(func(plugin *protogen.Plugin) error {
		plugin.SupportedFeatures = uint64(pluginpb.CodeGeneratorResponse_FEATURE_PROTO3_OPTIONAL)
		for _, file := range plugin.Files {
			if file.Generate {
				generateFile(plugin, file)
			}
		}
		return nil
	})
}

type sseMethod struct {
	service *protogen.Service
	method  *protogen.Method
	verb    string
	path    string
}

func generateFile(plugin *protogen.Plugin, file *protogen.File) {
	methods := collectSSEMethods(file)
	if len(methods) == 0 {
		return
	}

	filename := file.GeneratedFilenamePrefix + "_sse.pb.go"
	g := plugin.NewGeneratedFile(filename, file.GoImportPath)
	g.P("// Code generated by protoc-gen-go-sse. DO NOT EDIT.")
	g.P("// versions:")
	g.P("// - protoc-gen-go-sse ", version)
	g.P("// - protoc             ", protocVersion(plugin))
	g.P("// source: ", file.Desc.Path())
	g.P()
	g.P("package ", file.GoPackageName)
	g.P()

	grouped := map[*protogen.Service][]sseMethod{}
	for _, m := range methods {
		grouped[m.service] = append(grouped[m.service], m)
	}
	for _, service := range file.Services {
		items := grouped[service]
		if len(items) == 0 {
			continue
		}
		genService(g, service, items)
	}
}

func collectSSEMethods(file *protogen.File) []sseMethod {
	var out []sseMethod
	for _, service := range file.Services {
		for _, method := range service.Methods {
			rule, ok := proto.GetExtension(method.Desc.Options(), ssev1.E_ServerSentEvent).(*ssev1.StreamRule)
			if !ok || rule == nil {
				continue
			}
			verb, path := streamRuleHTTP(rule)
			if verb == "" || path == "" {
				continue
			}
			out = append(out, sseMethod{service: service, method: method, verb: verb, path: path})
		}
	}
	return out
}

func streamRuleHTTP(rule *ssev1.StreamRule) (string, string) {
	switch pattern := rule.GetPattern().(type) {
	case *ssev1.StreamRule_Get:
		return http.MethodGet, pattern.Get
	case *ssev1.StreamRule_Post:
		return http.MethodPost, pattern.Post
	default:
		return "", ""
	}
}

func genService(g *protogen.GeneratedFile, service *protogen.Service, methods []sseMethod) {
	serviceName := service.GoName
	contextIdent := g.QualifiedGoIdent(contextPackage.Ident("Context"))
	streamIdent := g.QualifiedGoIdent(ssePackage.Ident("Stream"))
	serverIdent := g.QualifiedGoIdent(khttpPackage.Ident("Server"))
	optionIdent := g.QualifiedGoIdent(kratosPackage.Ident("HTTPStreamOption"))

	g.P("type ", serviceName, "SSEServer interface {")
	for _, item := range methods {
		g.P(item.method.GoName, "(", contextIdent, ", *", item.method.Input.GoIdent, ", *", streamIdent, ") error")
	}
	g.P("}")
	g.P()

	g.P("func Register", serviceName, "SSEServer(s *", serverIdent, ", srv ", serviceName, "SSEServer, opts ...", optionIdent, ") {")
	for _, item := range methods {
		g.P("_", serviceName, "_", item.method.GoName, "_SSE_Register(s, srv, opts...)")
	}
	g.P("}")
	g.P()

	for _, item := range methods {
		genMethod(g, item)
	}
}

func genMethod(g *protogen.GeneratedFile, item sseMethod) {
	serviceName := item.service.GoName
	methodName := item.method.GoName
	input := item.method.Input.GoIdent
	operationConst := "Operation" + serviceName + methodName + "SSE"

	serverIdent := g.QualifiedGoIdent(khttpPackage.Ident("Server"))
	contextIdent := g.QualifiedGoIdent(khttpPackage.Ident("Context"))
	optionIdent := g.QualifiedGoIdent(kratosPackage.Ident("HTTPStreamOption"))
	registerIdent := g.QualifiedGoIdent(kratosPackage.Ident("RegisterHTTPStreamBound"))

	g.P("const ", operationConst, ` = "/`, item.method.Desc.Parent().FullName(), `/`, item.method.Desc.Name(), `"`)
	g.P()
	g.P("func _", serviceName, "_", methodName, "_SSE_Register(s *", serverIdent, ", srv ", serviceName, "SSEServer, opts ...", optionIdent, ") {")
	g.P(registerIdent, "(s, ", strconv.Quote(item.verb), ", ", strconv.Quote(item.path), ", ", operationConst, ",")
	g.P("func(ctx ", contextIdent, ", in *", input, ") error {")
	if item.verb == http.MethodGet {
		g.P("return ctx.BindQuery(in)")
	} else {
		g.P("return ctx.Bind(in)")
	}
	g.P("},")
	g.P("srv.", methodName, ",")
	g.P("opts...,")
	g.P(")")
	g.P("}")
	g.P()
}

func protocVersion(plugin *protogen.Plugin) string {
	v := plugin.Request.GetCompilerVersion()
	if v == nil {
		return "(unknown)"
	}
	var suffix string
	if v.GetSuffix() != "" {
		suffix = "-" + v.GetSuffix()
	}
	return strings.TrimPrefix(fmt.Sprintf("v%d.%d.%d%s", v.GetMajor(), v.GetMinor(), v.GetPatch(), suffix), "v0.0.0")
}
