// Package grpcx provides small gRPC server helpers.
package grpcx

import (
	"context"
	"encoding/json"
	"errors"
	"log/slog"
	"net"
	"net/netip"
	"runtime/debug"
	"strings"
	"time"

	kiterrors "github.com/crypto-zero/go-kit/errors"
	"google.golang.org/grpc"
	"google.golang.org/grpc/metadata"
	"google.golang.org/grpc/peer"
	"google.golang.org/grpc/status"
	"google.golang.org/protobuf/encoding/protojson"
	"google.golang.org/protobuf/proto"
)

const (
	codeOK = 200
	// codeClientClosedRequest is the nginx-convention status for requests the
	// client canceled; it keeps client cancellations below the 5xx alerting
	// threshold.
	codeClientClosedRequest = 499
	codeGatewayTimeout      = 504
	// serverErrorFloor is the first status code treated as a server fault and
	// logged at Error level; everything below logs at Warn.
	serverErrorFloor = 500
)

// overwriteIPHeaders are single-value client-IP headers that trusted edges
// (Cloudflare, nginx, Envoy) overwrite rather than append to; they outrank
// the append-style x-forwarded-for.
var overwriteIPHeaders = []string{"cf-connecting-ip", "x-real-ip"}

// LoggingOption configures gRPC server request logging.
type LoggingOption func(*loggingOptions)

type loggingOptions struct {
	component  string
	deviceKeys []string
	skipRedact bool
}

type redacter interface {
	Redact() string
}

// WithComponent sets the logged component field.
func WithComponent(component string) LoggingOption {
	return func(o *loggingOptions) {
		o.component = component
	}
}

// WithDeviceMetadataKeys sets metadata keys used to fill the device field.
func WithDeviceMetadataKeys(keys ...string) LoggingOption {
	return func(o *loggingOptions) {
		o.deviceKeys = append([]string(nil), keys...)
	}
}

// WithSkipRedact ignores the Redact method generated by protoc-gen-go-redact.
func WithSkipRedact() LoggingOption {
	return func(o *loggingOptions) {
		o.skipRedact = true
	}
}

// ErrorNormalization returns a unary interceptor that rewrites handler errors
// just before they leave the server. It should be the outermost interceptor,
// wrapping Logging, so server logs keep the original wrap chain while the
// client receives the sanitized form.
func ErrorNormalization() grpc.UnaryServerInterceptor {
	return func(
		ctx context.Context,
		req any,
		_ *grpc.UnaryServerInfo,
		handler grpc.UnaryHandler,
	) (any, error) {
		resp, err := handler(ctx, req)
		return resp, normalizeError(err)
	}
}

// normalizeError redacts kiterrors.FromError's unknown-error fallback — the
// only path that puts a raw err.Error() (SQL detail, dial targets, RPC URLs
// with API keys, etc.) into the client-visible message. Deliberate errors —
// kit error sentinels and explicit gRPC status errors — always pass through,
// even when they wrap a context error from an internal sub-call. Otherwise
// context terminations keep their canonical gRPC codes.
func normalizeError(err error) error {
	if err == nil {
		return nil
	}
	if !isUnknownError(kiterrors.FromError(err)) {
		return err
	}
	if errors.Is(err, context.Canceled) || errors.Is(err, context.DeadlineExceeded) {
		return status.FromContextError(err).Err()
	}
	return kiterrors.InternalServer("INTERNAL", "internal server error")
}

// isUnknownError reports whether e is kiterrors.FromError's unknown-error
// fallback rather than a deliberate error. normalizeError and errorFields
// must agree on this predicate: it decides both what the client receives and
// how the request is logged.
func isUnknownError(e *kiterrors.Error) bool {
	return e.Status == kiterrors.UnknownCode &&
		(e.Info == nil || e.Info.Reason == kiterrors.UnknownReason)
}

// MessageValidator validates a proto message. A protovalidate Validator's
// Validate method satisfies it after a trivial wrap:
//
//	grpcx.Validation(func(m proto.Message) error { return v.Validate(m) })
//
// Keeping the dependency at the call site lets grpcx stay free of the
// protovalidate (CEL) import.
type MessageValidator func(proto.Message) error

// ValidationOption configures the Validation interceptor.
type ValidationOption func(*validationOptions)

type validationOptions struct {
	errTemplate *kiterrors.Error
}

// WithValidationError sets the error returned on a validation failure. The
// template is cloned per failure and its message is replaced with the
// validator's detail, so a shared sentinel is never mutated. Defaults to a
// 400 VALIDATION_FAILED error.
func WithValidationError(err *kiterrors.Error) ValidationOption {
	return func(o *validationOptions) {
		if err != nil {
			o.errTemplate = err
		}
	}
}

// Validation returns a unary interceptor that runs validate against every
// incoming proto.Message request and rejects failures before the handler
// runs. A nil validate skips validation. The validator's detail is carried in
// the returned error's message.
func Validation(validate MessageValidator, opts ...ValidationOption) grpc.UnaryServerInterceptor {
	o := validationOptions{errTemplate: kiterrors.BadRequest("VALIDATION_FAILED", "validation failed")}
	for _, opt := range opts {
		opt(&o)
	}
	return func(ctx context.Context, req any, _ *grpc.UnaryServerInfo, handler grpc.UnaryHandler) (any, error) {
		if validate != nil {
			if msg, ok := req.(proto.Message); ok {
				if err := validate(msg); err != nil {
					rejected := o.errTemplate.Clone()
					rejected.Message = err.Error()
					return nil, rejected
				}
			}
		}
		return handler(ctx, req)
	}
}

// Recovery returns a unary interceptor that converts panics into internal errors.
func Recovery(logger *slog.Logger) grpc.UnaryServerInterceptor {
	logger = nonNilLogger(logger)
	return func(ctx context.Context, req any, info *grpc.UnaryServerInfo, handler grpc.UnaryHandler) (resp any, err error) {
		defer func() {
			if recovered := recover(); recovered != nil {
				logger.ErrorContext(ctx,
					"grpc panic recovered",
					"method", fullMethod(info),
					"panic", recovered,
					"stack", string(debug.Stack()),
				)
				err = kiterrors.InternalServer("INTERNAL", "internal server error")
			}
		}()
		return handler(ctx, req)
	}
}

// Logging returns a unary interceptor that writes one structured record per
// request with kratos-style fields: ip, device, kind, component, operation,
// args, reply, code, reason, latency (seconds) and err on failure. Payloads
// honor protoc-gen-go-redact unless WithSkipRedact is set.
func Logging(logger *slog.Logger, opts ...LoggingOption) grpc.UnaryServerInterceptor {
	logger = nonNilLogger(logger)
	options := newLoggingOptions(opts...)
	return func(ctx context.Context, req any, info *grpc.UnaryServerInfo, handler grpc.UnaryHandler) (any, error) {
		start := time.Now()
		resp, err := handler(ctx, req)
		latency := time.Since(start)
		operation := fullMethod(info)
		code, reason := errorFields(err)
		attrs := []any{
			"ip", ClientIP(ctx),
			"device", metadataValue(ctx, options.deviceKeys),
			"kind", "server",
			"component", options.component,
			"operation", operation,
			"args", logPayload(req, options),
			"reply", logPayload(resp, options),
			"code", code,
			"reason", reason,
			"latency", latency.Seconds(),
		}
		if err != nil {
			attrs = append(attrs, "err", err)
			logRequestFailure(ctx, logger, code, "grpc request failed", attrs...)
			return resp, err
		}
		logger.InfoContext(ctx, "grpc request completed", attrs...)
		return resp, nil
	}
}

// ClientIP returns the most likely client IP from incoming gRPC context metadata.
//
// Trust model: forwarded headers are client-supplied unless a trusted edge
// (Cloudflare, Envoy, nginx) strips or overwrites them — deploy behind such
// an edge for meaningful values, and treat the result as a logging hint, not
// an authorization input. Overwrite-style single-value headers set by a known
// edge (cf-connecting-ip, x-real-ip) take precedence over the append-style
// x-forwarded-for, from which the rightmost valid IP — the closest verifiable
// hop — is used. Values that do not parse as IP addresses are ignored.
func ClientIP(ctx context.Context) string {
	if md, ok := metadata.FromIncomingContext(ctx); ok {
		for _, key := range overwriteIPHeaders {
			values := md.Get(key)
			if len(values) == 0 {
				continue
			}
			if ip := canonicalIP(values[0]); ip != "" {
				return ip
			}
		}
		if values := md.Get("x-forwarded-for"); len(values) > 0 {
			if ip := rightmostValidIP(values[0]); ip != "" {
				return ip
			}
		}
	}
	if p, ok := peer.FromContext(ctx); ok && p.Addr != nil {
		host, _, err := net.SplitHostPort(p.Addr.String())
		if err != nil {
			return p.Addr.String()
		}
		return host
	}
	return ""
}

func newLoggingOptions(opts ...LoggingOption) loggingOptions {
	options := loggingOptions{
		component:  "grpc",
		deviceKeys: []string{"user-agent", "grpc-user-agent", "x-device", "x-client-device"},
	}
	for _, opt := range opts {
		opt(&options)
	}
	return options
}

func fullMethod(info *grpc.UnaryServerInfo) string {
	if info == nil {
		return ""
	}
	return info.FullMethod
}

func errorFields(err error) (code int, reason string) {
	if err == nil {
		return codeOK, ""
	}
	// Deliberate errors keep their own code even when they wrap a context
	// error from an internal sub-call; only the unknown fallback inspects
	// context termination, so client cancellations do not log as 500s.
	if isUnknownError(kiterrors.FromError(err)) {
		if errors.Is(err, context.Canceled) {
			return codeClientClosedRequest, "CANCELLED"
		}
		if errors.Is(err, context.DeadlineExceeded) {
			return codeGatewayTimeout, "DEADLINE_EXCEEDED"
		}
	}
	return kiterrors.Code(err), kiterrors.Reason(err)
}

// logRequestFailure logs a failed request at Error level for server faults
// and Warn level for everything else (client errors, cancellations).
func logRequestFailure(ctx context.Context, logger *slog.Logger, code int, msg string, attrs ...any) {
	if code >= serverErrorFloor {
		logger.ErrorContext(ctx, msg, attrs...)
		return
	}
	logger.WarnContext(ctx, msg, attrs...)
}

func nonNilLogger(logger *slog.Logger) *slog.Logger {
	if logger != nil {
		return logger
	}
	return slog.Default()
}

func metadataValue(ctx context.Context, keys []string) string {
	md, ok := metadata.FromIncomingContext(ctx)
	if !ok {
		return ""
	}
	for _, key := range keys {
		values := md.Get(key)
		if len(values) > 0 {
			return values[0]
		}
	}
	return ""
}

// rightmostValidIP picks the rightmost parseable IP from a comma-separated
// x-forwarded-for list: proxies append, so the right end is the closest
// verifiable hop while the left end is client-controlled.
func rightmostValidIP(list string) string {
	entries := strings.Split(list, ",")
	for i := len(entries) - 1; i >= 0; i-- {
		if ip := canonicalIP(entries[i]); ip != "" {
			return ip
		}
	}
	return ""
}

// canonicalIP parses value and returns its canonical string form, or "" when
// it is not an IP address.
func canonicalIP(value string) string {
	addr, err := netip.ParseAddr(strings.TrimSpace(value))
	if err != nil {
		return ""
	}
	return addr.String()
}

func logPayload(v any, o loggingOptions) any {
	if v == nil {
		return json.RawMessage("{}")
	}
	if r, ok := v.(redacter); ok && !o.skipRedact {
		return redactedPayload(r.Redact())
	}
	pm, ok := v.(proto.Message)
	if !ok {
		return v
	}
	data, err := protojson.MarshalOptions{
		UseProtoNames: true,
	}.Marshal(pm)
	if err != nil {
		return v
	}
	return json.RawMessage(data)
}

func redactedPayload(data string) any {
	if data == "" {
		return json.RawMessage("{}")
	}
	if json.Valid([]byte(data)) {
		return json.RawMessage(data)
	}
	return data
}
