// Package grpcx provides small gRPC server helpers.
package grpcx

import (
	"context"
	"encoding/json"
	"errors"
	"log/slog"
	"net"
	"runtime/debug"
	"strings"
	"time"

	kiterrors "github.com/crypto-zero/go-kit/errors"
	"google.golang.org/grpc"
	"google.golang.org/grpc/metadata"
	"google.golang.org/grpc/peer"
	"google.golang.org/grpc/status"
	"google.golang.org/protobuf/encoding/protojson"
	"google.golang.org/protobuf/proto"
)

const okCode = 200

// LoggingOption configures gRPC server request logging.
type LoggingOption func(*loggingOptions)

type loggingOptions struct {
	component  string
	deviceKeys []string
	skipRedact bool
}

type redacter interface {
	Redact() string
}

// WithLoggingComponent sets the logged component field.
func WithLoggingComponent(component string) LoggingOption {
	return func(o *loggingOptions) {
		o.component = component
	}
}

// WithDeviceMetadataKeys sets metadata keys used to fill the device field.
func WithDeviceMetadataKeys(keys ...string) LoggingOption {
	return func(o *loggingOptions) {
		o.deviceKeys = append([]string(nil), keys...)
	}
}

// WithSkipRedact ignores the Redact method generated by protoc-gen-go-redact.
func WithSkipRedact() LoggingOption {
	return func(o *loggingOptions) {
		o.skipRedact = true
	}
}

// ErrorNormalization returns a unary interceptor that rewrites handler errors
// just before they leave the server. It should be the outermost interceptor,
// wrapping Logging, so server logs keep the original wrap chain while the
// client receives the sanitized form.
func ErrorNormalization() grpc.UnaryServerInterceptor {
	return func(
		ctx context.Context,
		req any,
		_ *grpc.UnaryServerInfo,
		handler grpc.UnaryHandler,
	) (any, error) {
		resp, err := handler(ctx, req)
		if err != nil {
			return resp, normalizeError(err)
		}
		return resp, nil
	}
}

// normalizeError redacts kiterrors.FromError's unknown-error fallback — the
// only path that puts a raw err.Error() (SQL detail, dial targets, RPC URLs
// with API keys, etc.) into the client-visible message. Deliberate errors —
// kit error sentinels and explicit gRPC status errors — pass through
// untouched, and context terminations keep their canonical gRPC codes.
func normalizeError(err error) error {
	if errors.Is(err, context.Canceled) || errors.Is(err, context.DeadlineExceeded) {
		return status.FromContextError(err).Err()
	}
	e := kiterrors.FromError(err)
	if e.Status == kiterrors.UnknownCode &&
		(e.Info == nil || e.Info.Reason == kiterrors.UnknownReason) {
		return kiterrors.InternalServer("INTERNAL", "internal server error")
	}
	return err
}

// Recovery returns a unary interceptor that converts panics into internal errors.
func Recovery(logger *slog.Logger) grpc.UnaryServerInterceptor {
	logger = nonNilLogger(logger)
	return func(ctx context.Context, req any, info *grpc.UnaryServerInfo, handler grpc.UnaryHandler) (resp any, err error) {
		defer func() {
			if recovered := recover(); recovered != nil {
				logger.ErrorContext(ctx,
					"grpc panic recovered",
					"method", fullMethod(info),
					"panic", recovered,
					"stack", string(debug.Stack()),
				)
				err = kiterrors.InternalServer("INTERNAL", "internal server error")
			}
		}()
		return handler(ctx, req)
	}
}

// Logging returns a unary interceptor with kratos-compatible request fields.
func Logging(logger *slog.Logger, opts ...LoggingOption) grpc.UnaryServerInterceptor {
	logger = nonNilLogger(logger)
	options := newLoggingOptions(opts...)
	return func(ctx context.Context, req any, info *grpc.UnaryServerInfo, handler grpc.UnaryHandler) (any, error) {
		start := time.Now()
		resp, err := handler(ctx, req)
		latency := time.Since(start)
		method := fullMethod(info)
		code, reason := errorFields(err)
		attrs := []any{
			"ip", ClientIP(ctx),
			"device", metadataValue(ctx, options.deviceKeys),
			"kind", "server",
			"component", options.component,
			"operation", method,
			"method", method,
			"args", logPayload(req, options.skipRedact),
			"reply", logPayload(resp, options.skipRedact),
			"code", code,
			"reason", reason,
			"latency", latency.Seconds(),
			"duration", latency,
		}
		if err != nil {
			attrs = append(attrs, "err", err)
			logErrorContext(logger, ctx, code, "grpc request failed", attrs...)
			return resp, err
		}
		logger.InfoContext(ctx, "grpc request completed", attrs...)
		return resp, nil
	}
}

// ClientIP returns the most likely client IP from incoming gRPC context metadata.
func ClientIP(ctx context.Context) string {
	if md, ok := metadata.FromIncomingContext(ctx); ok {
		for _, key := range []string{"x-forwarded-for", "x-real-ip", "cf-connecting-ip"} {
			values := md.Get(key)
			if len(values) == 0 {
				continue
			}
			if ip := firstIP(values[0]); ip != "" {
				return ip
			}
		}
	}
	if p, ok := peer.FromContext(ctx); ok && p.Addr != nil {
		host, _, err := net.SplitHostPort(p.Addr.String())
		if err != nil {
			return p.Addr.String()
		}
		return host
	}
	return ""
}

func newLoggingOptions(opts ...LoggingOption) loggingOptions {
	options := loggingOptions{
		component:  "grpc",
		deviceKeys: []string{"user-agent", "grpc-user-agent", "x-device", "x-client-device"},
	}
	for _, opt := range opts {
		opt(&options)
	}
	return options
}

func fullMethod(info *grpc.UnaryServerInfo) string {
	if info == nil {
		return ""
	}
	return info.FullMethod
}

func errorFields(err error) (code int, reason string) {
	if err == nil {
		return okCode, ""
	}
	return kiterrors.Code(err), kiterrors.Reason(err)
}

func logErrorContext(logger *slog.Logger, ctx context.Context, code int, msg string, attrs ...any) {
	if code >= 500 {
		logger.ErrorContext(ctx, msg, attrs...)
		return
	}
	logger.WarnContext(ctx, msg, attrs...)
}

func nonNilLogger(logger *slog.Logger) *slog.Logger {
	if logger != nil {
		return logger
	}
	return slog.Default()
}

func metadataValue(ctx context.Context, keys []string) string {
	md, ok := metadata.FromIncomingContext(ctx)
	if !ok {
		return ""
	}
	for _, key := range keys {
		values := md.Get(key)
		if len(values) > 0 {
			return values[0]
		}
	}
	return ""
}

func firstIP(value string) string {
	if before, _, ok := strings.Cut(value, ","); ok {
		value = before
	}
	return strings.TrimSpace(value)
}

func logPayload(v any, skipRedact bool) any {
	if v == nil {
		return json.RawMessage("{}")
	}
	if r, ok := v.(redacter); ok && !skipRedact {
		return redactedPayload(r.Redact())
	}
	pm, ok := v.(proto.Message)
	if !ok {
		return v
	}
	data, err := protojson.MarshalOptions{
		UseProtoNames: true,
	}.Marshal(pm)
	if err != nil {
		return v
	}
	return json.RawMessage(data)
}

func redactedPayload(data string) any {
	if data == "" {
		return json.RawMessage("{}")
	}
	if json.Valid([]byte(data)) {
		return json.RawMessage(data)
	}
	return data
}
